@extends('layouts.app')

@section('title', 'Kalender - FocusDay')

@section('content')
<div class="container-fluid">
    <!-- Header Section -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h2 class="fw-bold text-dark mb-1">Kalender Rencana</h2>
                    <p class="text-muted mb-0">Lihat semua rencana Anda dalam sbulan</p>
                </div>
                <!-- Tombol Buka Form -->
                <button class="btn btn-success btn-add-task shadow-sm" data-bs-toggle="modal" data-bs-target="#addTaskModal" onclick="resetFormState()">
                    <i class="bi bi-plus-circle me-2"></i>Tambah Rencana
                </button>
            </div>
        </div>
    </div>
    
    <div class="row">
        <!-- Calendar Section -->
        <div class="col-lg-9 mb-4">
            <div class="card border-0 shadow-sm">
                <div class="card-body p-4">
                    <!-- Month Navigation -->
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <button class="btn btn-light" id="prevMonthBtn">
                            <i class="bi bi-chevron-left"></i>
                        </button>
                        <h4 class="fw-bold mb-0" id="monthLabel">Januari 2026</h4>
                        <button class="btn btn-light" id="nextMonthBtn">
                            <i class="bi bi-chevron-right"></i>
                        </button>
                    </div>
                    
                    <!-- Calendar Grid -->
                    <div class="calendar-grid" id="mainCalendarGrid">
                        <!-- Headers Statis -->
                        @php
                            $weekStart = (int) ((session('user')['week_start'] ?? 1));
                            $dayHeaders = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];
                            if ($weekStart === 1) {
                                $dayHeaders = ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'];
                            }
                        @endphp
                        @foreach ($dayHeaders as $h)
                            <div class="calendar-day-header">{{ $h }}</div>
                        @endforeach
                        
                        <!-- Days generated by JS -->
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Sidebar Legend -->
        <div class="col-lg-3">
            <div class="card border-0 shadow-sm mb-4">
                <div class="card-body p-4">
                    <h5 class="fw-semibold mb-3">
                        <i class="bi bi-palette me-2"></i>
                        Kategori
                    </h5>
                    
                    <div class="category-legend">
                        @forelse($categories as $cat)
                            @php
                                $warna = trim($cat->warna ?? '');
                                $warnaLower = strtolower($warna);
                                $colorMap = [
                                    'biru' => '#2563eb',
                                    'blue' => '#2563eb',
                                    'hijau' => '#10b981',
                                    'green' => '#10b981',
                                    'kuning' => '#f59e0b',
                                    'yellow' => '#f59e0b',
                                    'merah' => '#ef4444',
                                    'red' => '#ef4444',
                                    'ungu' => '#7c3aed',
                                    'purple' => '#7c3aed',
                                    'pink' => '#ec4899',
                                    'abu-abu' => '#9ca3af',
                                    'gray' => '#9ca3af',
                                    'grey' => '#9ca3af',
                                ];
                                $cssColor = $colorMap[$warnaLower] ?? ($warna ?: '#2563eb');
                            @endphp
                            <div class="legend-item">
                                <span class="legend-dot" style="background-color: {{ $cssColor }};"></span>
                                <span class="legend-label">{{ $cat->nama_kategori }}</span>
                            </div>
                        @empty
                            <div class="text-muted small">Belum ada kategori. Tambah kategori di halaman Kategori.</div>
                        @endforelse
                    </div>
                </div>
            </div>
            
            <!-- Quick Stats -->
            <div class="card border-0 shadow-sm quick-stats-card">
                <div class="card-body p-4">
                    <h5 class="fw-semibold mb-3">
                        <i class="bi bi-graph-up me-2 text-success"></i>
                        Statistik Bulan Ini
                    </h5>
                    
                    <div class="stat-item mb-3">
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="text-muted">Total Tugas</span>
                            <span class="fw-bold text-dark" id="statTotal">{{ $totalTasks }}</span>
                        </div>
                    </div>
                    
                    <div class="stat-item mb-3">
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="text-muted">Selesai</span>
                            <span class="fw-bold text-success" id="statCompleted">{{ $completedTasks }}</span>
                        </div>
                    </div>
                    
                    <div class="stat-item">
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="text-muted">Tertunda</span>
                            <span class="fw-bold text-warning" id="statOverdue">{{ $overdueTasks }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Task Detail Modal -->
<div class="modal fade" id="taskDetailModal" tabindex="-1" aria-labelledby="taskDetailModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-0 shadow">
            <div class="modal-header border-0">
                <h5 class="modal-title fw-bold" id="taskDetailModalLabel">Rencana - <span id="modalDate"></span></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="taskDetailBody">
                <!-- Tasks populated via JS -->
            </div>
            <!-- Modal Footer -->
            <div class="modal-footer border-0">
                <!-- Tombol Tambah Rencana (Always Available) -->
                <button type="button" class="btn btn-success" onclick="openAddTaskModalWithDate(selectedCalendarDateString)">
                    <i class="bi bi-plus-circle me-2"></i>Tambah Rencana
                </button>
                <!-- Tombol Tutup -->
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Tutup</button>
            </div>
        </div>
    </div>
</div>

<!-- ADD/EDIT TASK MODAL -->
<div class="modal fade" id="addTaskModal" tabindex="-1" aria-labelledby="addTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-0 shadow-lg">
            <!-- Modal Header -->
            <div class="modal-header border-0 pb-3" style="border-bottom: 1px solid #e5e7eb !important;">
                <div class="w-100 d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="modal-title fw-bold text-dark mb-0" id="addTaskModalLabel">
                            <i class="bi bi-plus-circle-fill me-2" style="color: #10b981;"></i>
                            <span id="formTitleText">Rencana Baru</span>
                        </h5>
                        <small class="text-muted" id="formSubtitleText">Isi detail tugas kamu</small>
                    </div>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="resetFormState()"></button>
                </div>
            </div>
            
            <div class="modal-body p-4 pt-3">
                <form id="taskForm" class="needs-validation" novalidate>
                    <!-- Judul Tugas -->
                    <div class="mb-4">
                        <label for="taskTitle" class="form-label fw-semibold text-dark">
                            <i class="bi bi-card-heading me-1 text-muted" style="font-size: 0.9rem;"></i>
                            Judul Tugas
                        </label>
                        <input type="text" 
                               class="form-control form-control-lg" 
                               id="taskTitle" 
                               placeholder="Contoh: Meeting dengan tim development" 
                               required
                               style="border-radius: 10px; border: 2px solid #e5e7eb; padding: 0.75rem 1rem;">
                        <div class="invalid-feedback">Harap isi judul tugas</div>
                    </div>
                    
                    <!-- Kategori -->
                    <div class="mb-4">
                        <label class="form-label fw-semibold text-dark d-flex justify-content-between align-items-center">
                            <span>
                                <i class="bi bi-tag me-1 text-muted" style="font-size: 0.9rem;"></i>
                                Kategori
                            </span>
                            <button type="button" class="btn btn-sm btn-outline-secondary border-0 p-0" 
                                    style="font-size: 0.8rem;" onclick="showAddCategory()">
                                <i class="bi bi-plus-circle me-1"></i>Tambah Kategori
                            </button>
                        </label>
                        <div class="d-flex flex-wrap gap-2" id="categorySelection">
                            @forelse($categories as $index => $category)
                                @php
                                    $inputId = 'categoryDb_' . $category->kategori_id;
                                    $isFirst = $index === 0;
                                    $warna = trim($category->warna ?? '');
                                    $warnaLower = strtolower($warna);
                                    $colorMap = [
                                        'biru' => ['bg' => '#dbeafe', 'text' => '#1e40af'],
                                        'blue' => ['bg' => '#dbeafe', 'text' => '#1e40af'],
                                        'hijau' => ['bg' => '#d1fae5', 'text' => '#065f46'],
                                        'green' => ['bg' => '#d1fae5', 'text' => '#065f46'],
                                        'kuning' => ['bg' => '#fef3c7', 'text' => '#92400e'],
                                        'yellow' => ['bg' => '#fef3c7', 'text' => '#92400e'],
                                        'merah' => ['bg' => '#fee2e2', 'text' => '#991b1b'],
                                        'red' => ['bg' => '#fee2e2', 'text' => '#991b1b'],
                                        'ungu' => ['bg' => '#ede9fe', 'text' => '#5b21b6'],
                                        'purple' => ['bg' => '#ede9fe', 'text' => '#5b21b6'],
                                        'pink' => ['bg' => '#fce7f3', 'text' => '#9d174d'],
                                        'abu-abu' => ['bg' => '#f3f4f6', 'text' => '#374151'],
                                        'gray' => ['bg' => '#f3f4f6', 'text' => '#374151'],
                                        'grey' => ['bg' => '#f3f4f6', 'text' => '#374151'],
                                    ];
                                    $darkMap = [
                                        'biru' => ['bg' => 'rgba(37, 99, 235, 0.15)', 'text' => '#93c5fd', 'border' => 'rgba(59, 130, 246, 0.3)'],
                                        'blue' => ['bg' => 'rgba(37, 99, 235, 0.15)', 'text' => '#93c5fd', 'border' => 'rgba(59, 130, 246, 0.3)'],
                                        'hijau' => ['bg' => 'rgba(16, 185, 129, 0.15)', 'text' => '#6ee7b7', 'border' => 'rgba(16, 185, 129, 0.3)'],
                                        'green' => ['bg' => 'rgba(16, 185, 129, 0.15)', 'text' => '#6ee7b7', 'border' => 'rgba(16, 185, 129, 0.3)'],
                                        'kuning' => ['bg' => 'rgba(245, 158, 11, 0.15)', 'text' => '#fcd34d', 'border' => 'rgba(245, 158, 11, 0.3)'],
                                        'yellow' => ['bg' => 'rgba(245, 158, 11, 0.15)', 'text' => '#fcd34d', 'border' => 'rgba(245, 158, 11, 0.3)'],
                                        'merah' => ['bg' => 'rgba(239, 68, 68, 0.15)', 'text' => '#fca5a5', 'border' => 'rgba(239, 68, 68, 0.3)'],
                                        'red' => ['bg' => 'rgba(239, 68, 68, 0.15)', 'text' => '#fca5a5', 'border' => 'rgba(239, 68, 68, 0.3)'],
                                        'ungu' => ['bg' => 'rgba(124, 58, 237, 0.15)', 'text' => '#ddd6fe', 'border' => 'rgba(124, 58, 237, 0.3)'],
                                        'purple' => ['bg' => 'rgba(124, 58, 237, 0.15)', 'text' => '#ddd6fe', 'border' => 'rgba(124, 58, 237, 0.3)'],
                                        'pink' => ['bg' => 'rgba(236, 72, 153, 0.15)', 'text' => '#fbcfe8', 'border' => 'rgba(236, 72, 153, 0.3)'],
                                        'abu-abu' => ['bg' => 'rgba(156, 163, 175, 0.15)', 'text' => '#e5e7eb', 'border' => 'rgba(156, 163, 175, 0.3)'],
                                        'gray' => ['bg' => 'rgba(156, 163, 175, 0.15)', 'text' => '#e5e7eb', 'border' => 'rgba(156, 163, 175, 0.3)'],
                                        'grey' => ['bg' => 'rgba(156, 163, 175, 0.15)', 'text' => '#e5e7eb', 'border' => 'rgba(156, 163, 175, 0.3)'],
                                    ];
                                    $cssBg = $colorMap[$warnaLower]['bg'] ?? '#f3f4f6';
                                    $cssText = $colorMap[$warnaLower]['text'] ?? '#374151';
                                    $darkBg = $darkMap[$warnaLower]['bg'] ?? 'rgba(156, 163, 175, 0.15)';
                                    $darkText = $darkMap[$warnaLower]['text'] ?? '#e5e7eb';
                                    $darkBorder = $darkMap[$warnaLower]['border'] ?? 'rgba(156, 163, 175, 0.3)';
                                @endphp
                                <input type="radio" class="btn-check" name="taskCategory" id="{{ $inputId }}" value="{{ $category->kategori_id }}" autocomplete="off" @checked($isFirst)>
                                <label class="btn btn-sm btn-category" for="{{ $inputId }}" style="--pill-bg: {{ $cssBg }}; --pill-text: {{ $cssText }}; --pill-bg-dark: {{ $darkBg }}; --pill-text-dark: {{ $darkText }}; --pill-border-dark: {{ $darkBorder }};">
                                    <i class="bi bi-tag me-1"></i>{{ $category->nama_kategori }}
                                </label>
                            @empty
                                <span class="text-muted small" id="emptyCategoryHint">Belum ada kategori. Tambah kategori dulu.</span>
                            @endforelse

                            <div id="additionalCategories"></div>
                        </div>
                    </div>
                    
                    <!-- WIDGET TANGGAL & WAKTU -->
                    <div class="mb-4" id="datetimeSection">
                        <label class="form-label fw-semibold text-dark mb-3">
                            <i class="bi bi-clock me-1 text-muted" style="font-size: 0.9rem;"></i>
                            Tanggal & Waktu
                        </label>
                        
                        <div class="datetime-wrapper">
                            <!-- BAGIAN TANGGAL -->
                            <div class="date-section" id="dateWidget">
                                <div class="custom-input-box" id="dateDisplayBox">
                                    <span class="date-display-text" id="dateText">Thursday, January 8</span>
                                    <!-- CALENDAR POPUP -->
                                    <div class="calendar-popup" id="calendarPopup">
                                        <div class="calendar-header">
                                            <button type="button" class="calendar-nav-btn" id="prevMonth">&lt;</button>
                                            <span class="calendar-month-title" id="calendarTitle">January 2026</span>
                                            <button type="button" class="calendar-nav-btn" id="nextMonth">&gt;</button>
                                        </div>
                                        <div class="calendar-grid" id="modalCalendarGrid">
                                            <!-- JS generated -->
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- BAGIAN WAKTU -->
                            <div class="time-section">
                                <div class="custom-input-box" id="timeDisplayBox">
                                    <div class="time-input-group" id="startTimeGroup">
                                        <input type="text" id="startTimeInput" value="7:30pm" placeholder="Start" autocomplete="off">
                                        <div class="time-dropdown" id="startTimeDropdown"></div>
                                    </div>
                                    <span class="time-separator">–</span>
                                    <div class="time-input-group" id="endTimeGroup">
                                        <input type="text" id="endTimeInput" value="8:30pm" placeholder="End" autocomplete="off">
                                        <div class="time-dropdown" id="endTimeDropdown"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-check form-check-inline mt-2" style="margin-left: 5px;">
                            <input class="form-check-input" type="checkbox" id="noSpecificTime">
                            <label class="form-check-label text-muted" for="noSpecificTime" style="font-size: 0.85rem;">
                                Tanpa waktu spesifik
                            </label>
                        </div>
                    </div>
                    
                    <!-- Catatan -->
                    <div class="mb-3">
                        <label for="taskNotes" class="form-label fw-semibold text-dark">
                            <i class="bi bi-sticky me-1 text-muted" style="font-size: 0.9rem;"></i>
                            Catatan <span class="text-muted fw-normal">(Opsional)</span>
                        </label>
                        <textarea class="form-control" 
                                  id="taskNotes" 
                                  rows="2" 
                                  placeholder="Tambahkan detail, link, atau catatan penting..."
                                  style="border-radius: 10px; border: 2px solid #e5e7eb; resize: none;"></textarea>
                        <div class="d-flex justify-content-between mt-1">
                            <small class="text-muted" style="font-size: 0.75rem;">
                                <i class="bi bi-info-circle me-1"></i>
                                Kosongkan waktu untuk tugas tanpa deadline spesifik
                            </small>
                            <small class="text-muted char-count" style="font-size: 0.75rem;">
                                <span id="charCount">0</span>/300
                            </small>
                        </div>
                    </div>
                </form>
                
                <!-- Form tambah kategori -->
                <div class="border-top mt-4 pt-3 d-none" id="addCategoryForm">
                    <label class="form-label fw-semibold text-dark mb-2">
                        <i class="bi bi-plus-circle me-1 text-success"></i>
                        Tambah Kategori Baru
                    </label>
                    <div class="input-group input-group-sm">
                        <input type="text" 
                               class="form-control" 
                               id="newCategoryName" 
                               placeholder="Nama kategori baru"
                               style="border-radius: 8px 0 0 8px;">
                        <select class="form-select" id="newCategoryColor" aria-label="Pilih warna kategori" style="max-width: 140px;">
                            <option value="biru" selected>Biru</option>
                            <option value="hijau">Hijau</option>
                            <option value="kuning">Kuning</option>
                            <option value="merah">Merah</option>
                            <option value="ungu">Ungu</option>
                            <option value="pink">Pink</option>
                            <option value="abu-abu">Abu-abu</option>
                        </select>
                        <button class="btn btn-outline-success" type="button" onclick="addNewCategory()" aria-label="Simpan kategori" style="border-radius: 0;">
                            <i class="bi bi-check-lg"></i>
                        </button>
                        <button class="btn btn-outline-danger" type="button" onclick="cancelAddCategory()" aria-label="Batal" style="border-radius: 0 8px 8px 0;">
                            <i class="bi bi-x-lg"></i>
                        </button>
                    </div>
                </div>
            </div>
            
            <!-- Modal Footer -->
            <div class="modal-footer border-0 pt-0">
                <button type="button" class="btn btn-light btn-lg px-4" data-bs-dismiss="modal" onclick="resetFormState()" style="border-radius: 10px;">
                    Batal
                </button>
                <button type="button" class="btn btn-success btn-lg px-4" onclick="saveTask()" id="submitTaskBtn" style="border-radius: 10px;">
                    <i class="bi bi-plus-circle me-2"></i><span id="btnText">Tambah Tugas</span>
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-sm">
        <div class="modal-content border-0 shadow-lg" style="border-radius: 12px;">
            <div class="modal-body p-4 text-center">
                <div class="mb-3">
                    <i class="bi bi-exclamation-circle text-warning display-4"></i>
                </div>
                <h5 class="fw-bold mb-2">Hapus Rencana?</h5>
                <p class="text-muted small mb-4">Apakah Anda yakin ingin menghapus rencana ini? Tindakan ini tidak dapat dibatalkan.</p>
                <div class="d-flex gap-2 justify-content-center">
                    <button type="button" class="btn btn-light w-100" data-bs-dismiss="modal" style="border-radius: 8px;">Batal</button>
                    <button type="button" class="btn btn-danger w-100" id="confirmDeleteBtn" style="border-radius: 8px;">Hapus</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Toast Notification -->
<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
    <div id="successToast" class="toast align-items-center text-white bg-success border-0 shadow" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body d-flex align-items-center">
                <i class="bi bi-check-circle-fill me-2" style="font-size: 1.2rem;"></i>
                <div>
                    <strong id="toastMessage">Rencana berhasil disimpan!</strong>
                    <div class="small" id="toastSubMessage">Tugas telah masuk ke kalender</div>
                </div>
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

@endsection

@push('styles')
<style>
    /* =========================================
       1. ORIGINAL CALENDAR PAGE STYLES
       ========================================= */
    
    .quick-stats-card {
        background: linear-gradient(135deg, #f0fdf4 0%, #ffffff 100%);
    }

    html[data-theme="dark"] .quick-stats-card {
        background: linear-gradient(135deg, rgba(16, 185, 129, 0.12) 0%, rgba(15, 23, 42, 0.75) 100%);
    }

    .calendar-grid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 8px;
    }
    
    .calendar-day-header {
        text-align: center;
        font-weight: 600;
        color: #6b7280;
        padding: 0.75rem 0;
        font-size: 0.875rem;
    }

    html[data-theme="dark"] .calendar-day-header {
        color: #94a3b8;
    }
    
    .calendar-day {
        aspect-ratio: 1;
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 0.5rem;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: flex-start;
        cursor: pointer;
        transition: all 0.2s ease;
        background-color: #ffffff;
        position: relative;
    }

    html[data-theme="dark"] .calendar-day {
        border-color: #1f2937;
        background-color: rgba(15, 23, 42, 0.85);
    }
    
    .calendar-day:hover {
        border-color: var(--primary-green);
        background-color: #f0fdf4;
        transform: scale(1.05);
        box-shadow: 0 2px 8px rgba(16, 185, 129, 0.15);
    }

    html[data-theme="dark"] .calendar-day:hover {
        background-color: rgba(16, 185, 129, 0.08);
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.35);
    }
    
    .calendar-day.today {
        background: linear-gradient(135deg, var(--primary-green-light), #ffffff);
        border: 2px solid var(--primary-green);
    }

    html[data-theme="dark"] .calendar-day.today {
        background: linear-gradient(135deg, rgba(16, 185, 129, 0.18), rgba(15, 23, 42, 0.85));
        border: 2px solid var(--primary-green);
    }
    
    .calendar-day.today .day-number {
        color: var(--primary-green-dark);
        font-weight: 700;
    }

    html[data-theme="dark"] .calendar-day.today .day-number {
        color: var(--primary-green);
    }
    
    .calendar-day.other-month {
        background-color: #f9fafb;
        color: #d1d5db;
        cursor: default;
    }

    html[data-theme="dark"] .calendar-day.other-month {
        background-color: rgba(255, 255, 255, 0.02);
        color: #475569;
    }
    
    .calendar-day.other-month:hover {
        transform: none;
        border-color: #e5e7eb;
        background-color: #f9fafb;
    }
    
    .day-number {
        font-weight: 600;
        color: #1f2937;
        font-size: 0.875rem;
        margin-bottom: 0.25rem;
    }

    html[data-theme="dark"] .day-number {
        color: #e2e8f0;
    }
    
    .task-indicators {
        display: flex;
        gap: 3px;
        flex-wrap: wrap;
        justify-content: center;
        margin-top: auto;
    }
    
    .task-dot {
        width: 6px;
        height: 6px;
        border-radius: 50%;
        display: inline-block;
    }
    
    .task-dot-work { background-color: #2563eb; }
    .task-dot-learning { background-color: #10b981; }
    .task-dot-personal { background-color: #f59e0b; }
    
    /* Legend Styles */
    .category-legend { display: flex; flex-direction: column; gap: 0.875rem; }
    .legend-item { display: flex; align-items: center; gap: 0.75rem; }
    .legend-dot { width: 12px; height: 12px; border-radius: 50%; }
    .legend-label { font-weight: 500; color: #4b5563; font-size: 0.875rem; }

    html[data-theme="dark"] .legend-label { color: #cbd5e1; }
    
    .stat-item { padding-bottom: 0.75rem; border-bottom: 1px solid #e5e7eb; }
    html[data-theme="dark"] .stat-item { border-bottom: 1px solid #1f2937; }
    .stat-item:last-child { border-bottom: none; padding-bottom: 0; }
    
    .btn-light {
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 0.5rem 1rem;
        transition: all 0.2s ease;
    }
    html[data-theme="dark"] .btn-light { border-color: #1f2937; }
    .btn-light:hover { background-color: var(--bg-light); border-color: #d1d5db; }
    
    /* Modal Styles */
    .modal-content { border-radius: 16px; }
    
    /* Task Item in Modal with Checkbox */
    .task-item-modal-wrapper {
        padding: 1rem;
        border-left: 3px solid;
        background-color: #f9fafb;
        border-radius: 8px;
        margin-bottom: 0.875rem;
        transition: all 0.2s ease;
    }
    
    html[data-theme="dark"] .task-item-modal-wrapper {
        background-color: rgba(255, 255, 255, 0.03);
    }
    
    .task-item-modal-wrapper:hover {
        background-color: #f3f4f6;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
    }
    
    html[data-theme="dark"] .task-item-modal-wrapper:hover {
        background-color: rgba(255, 255, 255, 0.05);
    }
    
    /* Checkbox Styling */
    .task-checkbox-wrapper {
        flex-shrink: 0;
        padding-top: 2px;
    }

    .task-completed {
        text-decoration: line-through !important;
        text-decoration-thickness: 2px !important;
        text-decoration-color: #10b981 !important;
        color: #9ca3af !important;
        opacity: 0.7;
    }

    html[data-theme="dark"] .task-completed {
        color: #9ca3af !important;
    }

    .form-check-input.task-checkbox {
        width: 1.2rem;
        height: 1.2rem;
        cursor: pointer;
        border: 2px solid #d1d5db;
        transition: all 0.2s ease;
    }

    .form-check-input.task-checkbox:checked {
        background-color: #10b981;
        border-color: #10b981;
    }

    .form-check-input.task-checkbox:focus {
        box-shadow: 0 0 0 0.25rem rgba(16, 185, 129, 0.25);
    }

    .form-check-input.task-checkbox:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }
    
    /* Time and Edit Icon Wrapper */
    .task-time-edit-wrapper {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        position: relative;
    }
    
    /* Edit Icon - Hidden by default */
    .task-edit-icon {
        opacity: 0;
        visibility: hidden;
        transform: translateX(-5px);
        transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
        text-decoration: none;
        border: none;
        background: transparent;
    }
    
    .task-item-modal-wrapper:hover .task-edit-icon {
        opacity: 1;
        visibility: visible;
        transform: translateX(0);
    }
    
    .task-edit-icon:hover {
        background-color: transparent !important;
    }
    
    .task-edit-icon i {
        font-size: 0.95rem;
        transition: transform 0.2s ease;
        color: inherit;
        opacity: inherit;
    }
    
    .task-edit-icon:hover i {
        transform: scale(1.1);
    }
    
    /* Task Time Text */
    .task-time-text {
        white-space: nowrap;
        transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1);
    }
    
    .task-item-modal-wrapper:hover .task-time-text {
        transform: translateX(-3px);
    }

    /* Old task modal classes - keeping for backward compatibility if needed */
    .task-item-modal.task-work { border-left-color: #2563eb; }
    .task-item-modal.task-learning { border-left-color: #10b981; }
    .task-item-modal.task-personal { border-left-color: #f59e0b; }
    
    .task-item-modal:last-child { margin-bottom: 0; }

    .empty-plan {
        padding: 1rem;
        border: 1px dashed #e5e7eb;
        border-radius: 12px;
        background-color: #f9fafb;
    }

    html[data-theme="dark"] .empty-plan {
        border-color: #1f2937;
        background-color: rgba(255, 255, 255, 0.03);
    }

    /* =========================================
       2. FORM MODAL STYLES
       ========================================= */
    
    #addTaskModal .modal-dialog { max-width: 560px; margin: 1.75rem auto; }
    #addTaskModal .modal-content { border-radius: 16px; }
    #addTaskModal .modal-body { position: relative; overflow-y: auto; max-height: 70vh; }

    .btn-add-task, .btn-success {
        background-color: #10b981 !important;
        border-color: #10b981 !important;
        font-weight: 500;
        border-radius: 10px;
        transition: all 0.2s ease;
    }
    .btn-add-task:hover, .btn-success:hover {
        background-color: #059669 !important;
        transform: translateY(-1px);
    }

    .btn-category {
        padding: 0.4rem 0.8rem;
        border-radius: 20px;
        border: 2px solid transparent;
        font-size: 0.85rem;
        transition: all 0.2s ease;
        font-weight: 500;
        background-color: var(--pill-bg, #f3f4f6) !important;
        color: var(--pill-text, #374151) !important;
        border-color: var(--pill-bg, #f3f4f6) !important;
    }

    html[data-theme="dark"] .btn-category {
        background-color: var(--pill-bg-dark, rgba(148, 163, 184, 0.12)) !important;
        color: var(--pill-text-dark, #e5e7eb) !important;
        border-color: var(--pill-border-dark, rgba(148, 163, 184, 0.25)) !important;
    }

    .btn-check:checked + .btn-category {
        border-color: #10b981;
        box-shadow: 0 0 0 2px rgba(16, 185, 129, 0.2);
        transform: translateY(-1px);
    }

    /* Widget Styling */
    .datetime-wrapper { display: flex; gap: 12px; margin-bottom: 1.5rem; }

    .custom-input-box {
        background-color: #ffffff;
        border: 1px solid #e5e7eb;
        color: #111827;
        border-radius: 10px;
        padding: 12px 16px;
        cursor: pointer;
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        user-select: none;
        min-height: 48px;
        transition: all 0.2s;
        box-shadow: 0 1px 2px rgba(0,0,0,0.05);
    }

    .custom-input-box:hover { border-color: #d1d5db; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }
    .custom-input-box.active { border-color: #10b981 !important; box-shadow: 0 0 0 3px rgba(16, 185, 129, 0.15) !important; }

    html[data-theme="dark"] .custom-input-box {
        background-color: #374151;
        border-color: #4b5563;
        color: #f9fafb;
        box-shadow: none;
    }
    html[data-theme="dark"] .custom-input-box:hover { background-color: #4b5563; }

    .date-display-text { font-size: 0.95rem; font-weight: 500; }
    
    .time-section { flex: 1.5; display: flex; align-items: center; justify-content: center; gap: 8px; }
    .time-input-group { display: flex; align-items: center; gap: 4px; padding: 2px 6px; border-radius: 6px; position: relative; cursor: text; min-width: 85px; justify-content: center; }
    
    html:not([data-theme="dark"]) .time-input-group { background: rgba(0,0,0,0.03); }
    html:not([data-theme="dark"]) .time-input-group:hover { background: rgba(0,0,0,0.06); }

    html[data-theme="dark"] .time-input-group { background: rgba(255,255,255,0.1); }
    html[data-theme="dark"] .time-input-group:hover { background: rgba(255,255,255,0.2); }

    .time-input-group input { background: transparent; border: none; width: 100%; outline: none; text-align: center; font-weight: 500; font-size: 0.9rem; text-transform: lowercase; cursor: text; }
    html:not([data-theme="dark"]) .time-input-group input { color: #111827; }
    html[data-theme="dark"] .time-input-group input { color: #ffffff; }
    
    .time-separator { opacity: 0.5; font-weight: 300; pointer-events: none; }

    /* CALENDAR POPUP (INSIDE MODAL) */
    .calendar-popup {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: #ffffff;
        border-radius: 16px;
        box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
        width: 320px;
        z-index: 2000;
        padding: 20px;
        display: none;
        border: 1px solid #e5e7eb;
        animation: fadeInScale 0.2s cubic-bezier(0.16, 1, 0.3, 1);
    }
    
    html[data-theme="dark"] .calendar-popup {
        background: #1f2937;
        border-color: #374151;
    }

    .calendar-popup.show { display: block; }
    .calendar-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
    .calendar-month-title { font-weight: 700; font-size: 1.1rem; }
    
    html:not([data-theme="dark"]) .calendar-month-title { color: #111827; }
    html[data-theme="dark"] .calendar-month-title { color: #f3f4f6; }

    .calendar-nav-btn { background: none; border: none; cursor: pointer; padding: 4px; border-radius: 50%; transition: background 0.2s; color: #6b7280; }
    .calendar-nav-btn:hover { background: #f3f4f6; color: #111827; }
    html[data-theme="dark"] .calendar-nav-btn:hover { background: #374151; color: white; }

    #modalCalendarGrid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 4px;
        text-align: center;
    }
    
    .calendar-day-label { font-size: 0.75rem; font-weight: 600; padding-bottom: 10px; text-transform: uppercase; color: #9ca3af; }
    
    #modalCalendarGrid .calendar-day { 
        width: 36px; height: 36px; display: flex; align-items: center; justify-content: center; 
        font-size: 0.95rem; border-radius: 50%; cursor: pointer; margin: 0 auto; transition: all 0.2s; 
        background: transparent; border: none; aspect-ratio: auto;
    }
    
    html:not([data-theme="dark"]) #modalCalendarGrid .calendar-day { color: #374151; }
    html:not([data-theme="dark"]) #modalCalendarGrid .calendar-day:hover:not(.selected) { background-color: #f3f4f6; }
    html:not([data-theme="dark"]) #modalCalendarGrid .calendar-day.other-month { color: #e5e7eb; }
    
    html[data-theme="dark"] #modalCalendarGrid .calendar-day { color: #d1d5db; }
    html[data-theme="dark"] #modalCalendarGrid .calendar-day:hover:not(.selected) { background-color: #374151; }
    html[data-theme="dark"] #modalCalendarGrid .calendar-day.other-month { color: #374151; }

    #modalCalendarGrid .calendar-day.selected { background-color: #10b981 !important; color: white !important; font-weight: 600; box-shadow: 0 4px 6px -1px rgba(16, 185, 129, 0.4); }
    #modalCalendarGrid .calendar-day.today { border: 2px solid #10b981; }
    #modalCalendarGrid .calendar-day.empty { cursor: default; }

    /* TIME DROPDOWN */
    .time-dropdown {
        position: absolute;
        top: 110%; left: 0;
        background: #ffffff;
        border-radius: 8px;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
        width: 130px;
        max-height: 250px;
        overflow-y: auto;
        z-index: 2000;
        display: none;
        border: 1px solid #e5e7eb;
        padding: 4px;
    }
    
    html[data-theme="dark"] .time-dropdown {
        background: #1f2937;
        border-color: #374151;
    }

    .time-dropdown.show { display: block; }
    .time-option { padding: 6px 10px; font-size: 0.85rem; border-radius: 4px; cursor: pointer; text-transform: lowercase; transition: all 0.1s; }
    
    html:not([data-theme="dark"]) .time-option { color: #374151; }
    html:not([data-theme="dark"]) .time-option:hover { background-color: #f3f4f6; color: #10b981; }
    
    html[data-theme="dark"] .time-option { color: #e5e7eb; }
    html[data-theme="dark"] .time-option:hover { background-color: #374151; color: #10b981; }

    .time-option.highlighted { background-color: #10b981; color: white; }

    @keyframes fadeInScale {
        from { opacity: 0; transform: translate(-50%, -45%); }
        to { opacity: 1; transform: translate(-50%, -50%); }
    }

    .datetime-wrapper.disabled .custom-input-box { opacity: 0.5; pointer-events: none; filter: grayscale(0.8); }
    
    /* Edit Mode Visuals */
    .is-editing-mode .modal-title i { color: #f59e0b !important; }
    .is-editing-mode #submitTaskBtn { background-color: #f59e0b !important; border-color: #f59e0b !important; }
    .is-editing-mode #submitTaskBtn:hover { background-color: #d97706 !important; }

    /* ============================================
       MOBILE RESPONSIVE FOR CALENDAR
       ============================================ */
    @media (max-width: 992px) {
        /* Stack sidebar on tablet */
        .col-lg-9, .col-lg-3 {
            margin-bottom: 1rem;
        }
    }
    
    @media (max-width: 768px) {
        /* Smaller calendar cells */
        .calendar-day {
            padding: 0.25rem;
            font-size: 0.8rem;
        }
        
        .day-number {
            font-size: 0.75rem;
        }
        
        .task-dot {
            width: 4px;
            height: 4px;
        }
        
        .calendar-day-header {
            font-size: 0.75rem;
            padding: 0.5rem 0;
        }
        
        /* Month navigation */
        #monthLabel {
            font-size: 1.125rem;
        }
    }
    
    @media (max-width: 576px) {
        .datetime-wrapper { flex-direction: column; }
        .date-section, .time-section { width: 100%; flex: auto; }
        
        /* Even smaller calendar for mobile */
        .calendar-grid {
            gap: 4px;
        }
        
        .calendar-day {
            padding: 0.2rem;
            border-radius: 6px;
        }
        
        .day-number {
            font-size: 0.7rem;
            margin-bottom: 0.125rem;
        }
        
        .task-indicators {
            gap: 2px;
        }
        
        .task-dot {
            width: 3px;
            height: 3px;
        }
        
        /* Legend more compact */
        .legend-item {
            font-size: 0.8rem;
        }
        
        .legend-dot {
            width: 10px;
            height: 10px;
        }
        
        /* Header actions stack */
        .row.mb-4 .d-flex {
            flex-direction: column;
            align-items: flex-start !important;
        }
        
        .row.mb-4 .btn {
            width: 100%;
            margin-top: 0.5rem;
        }
    }
</style>
@endpush

@push('scripts')
<script>
    // ============================
    // 1. DATA & STATE MANAGEMENT
    // ============================
    
    // State Editing
    let isEditing = false;
    let editTargetDate = null;
    let editTargetIndex = null;
    let editTargetPlanId = null;

    // Data rencana asli dari backend (tabel rencana + kategori)
    const backendPlans = @json($plans);

    // Mapping warna kategori ke warna hex yang dipakai di kalender
    function resolveCategoryColor(rawColor) {
        // Jika tidak ada warna/kategori, pakai abu-abu sebagai default
        if (!rawColor) return '#9ca3af'; // gray-400

        const lower = String(rawColor).trim().toLowerCase();
        const map = {
            'biru': '#2563eb',
            'blue': '#2563eb',
            'hijau': '#10b981',
            'green': '#10b981',
            'kuning': '#f59e0b',
            'yellow': '#f59e0b',
            'merah': '#ef4444',
            'red': '#ef4444',
            'ungu': '#7c3aed',
            'purple': '#7c3aed',
            'pink': '#ec4899',
            'abu-abu': '#9ca3af',
            'gray': '#9ca3af',
            'grey': '#9ca3af',
        };
        // Kalau warna dikenali di map → pakai itu, kalau tidak → pakai nilai aslinya
        // (fallback terakhir tetap abu-abu kalau entah kenapa masih falsy)
        return map[lower] || rawColor || '#9ca3af';
    }

    const rawPlans = (backendPlans || []).map(p => ({
        id: p.id,
        title: p.judul_tugas,
        date: p.tanggal,
        time: p.waktu,
        notes: p.catatan,
        status: p.status,
        category_id: p.kategori_id,
        category_name: p.nama_kategori,
        color: resolveCategoryColor(p.warna),
    }));

    // Group per tanggal supaya lebih mudah dipakai kalender & modal
    const tasksData = {};
    (rawPlans || []).forEach(plan => {
        if (!plan.date) return;
        if (!tasksData[plan.date]) tasksData[plan.date] = [];
        tasksData[plan.date].push(plan);
    });

    const monthNames = [
        "Januari", "Februari", "Maret", "April", "Mei", "Juni",
        "Juli", "Agustus", "September", "Oktober", "November", "Desember"
    ];

    let currentCalendarDate = new Date();
    let selectedCalendarDateString = null;

    const weekStart = {{ (int) ((session('user')['week_start'] ?? 1)) }};

    document.addEventListener('DOMContentLoaded', () => {
        renderCalendar();
        setupMainCalendarListeners();
        setupModalFormLogic();
        updateStats();
    });

    function updateStats() {
        let total = 0;
        Object.values(tasksData).forEach(dayTasks => {
            total += dayTasks.length;
        });
        document.getElementById('statTotal').innerText = total;
    }

    function setupMainCalendarListeners() {
        document.getElementById('prevMonthBtn').addEventListener('click', () => {
            currentCalendarDate.setMonth(currentCalendarDate.getMonth() - 1);
            renderCalendar();
        });

        document.getElementById('nextMonthBtn').addEventListener('click', () => {
            currentCalendarDate.setMonth(currentCalendarDate.getMonth() + 1);
            renderCalendar();
        });
    }

    function renderCalendar() {
        const year = currentCalendarDate.getFullYear();
        const month = currentCalendarDate.getMonth();
        document.getElementById('monthLabel').innerText = `${monthNames[month]} ${year}`;
        const calendarGrid = document.getElementById('mainCalendarGrid');
        
        const headers = Array.from(document.querySelectorAll('.calendar-day-header'));
        calendarGrid.innerHTML = '';
        headers.forEach(header => calendarGrid.appendChild(header));

        const firstDayIndexRaw = new Date(year, month, 1).getDay();
        const firstDayIndex = (firstDayIndexRaw - weekStart + 7) % 7;
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const daysInPrevMonth = new Date(year, month, 0).getDate();
        const today = new Date();
        
        // Previous Month
        for (let i = firstDayIndex; i > 0; i--) {
            const dayDiv = document.createElement('div');
            dayDiv.classList.add('calendar-day', 'other-month');
            dayDiv.innerHTML = `<span class="day-number">${daysInPrevMonth - i + 1}</span>`;
            calendarGrid.appendChild(dayDiv);
        }

        // Current Month
        for (let i = 1; i <= daysInMonth; i++) {
            const dayDiv = document.createElement('div');
            dayDiv.classList.add('calendar-day');
            const dateString = `${year}-${String(month + 1).padStart(2, '0')}-${String(i).padStart(2, '0')}`;
            dayDiv.setAttribute('data-date', dateString);

            if (i === today.getDate() && month === today.getMonth() && year === today.getFullYear()) {
                dayDiv.classList.add('today');
            }

            let indicatorsHtml = '';
            const tasks = tasksData[dateString];
            if (tasks && tasks.length > 0) {
                indicatorsHtml += `<div class="task-indicators">`;
                tasks.forEach(task => {
                    // Default abu-abu kalau tidak ada kategori/warna
                    const color = task.color || '#9ca3af';
                    indicatorsHtml += `<span class="task-dot" style="background-color: ${color};"></span>`;
                });
                indicatorsHtml += `</div>`;
            }

            dayDiv.innerHTML = `<span class="day-number">${i}</span>${indicatorsHtml}`;

            dayDiv.addEventListener('click', function() {
                const date = this.getAttribute('data-date');
                const dayTasks = tasksData[date];
                showTaskDetails(date, dayTasks || []);
            });

            calendarGrid.appendChild(dayDiv);
        }
    }

    // Helper to render the inner list HTML without touching the modal instance
    function renderTaskDetailList(date, tasks) {
        // Update selected global date just in case
        selectedCalendarDateString = date; 
        
        const dateObj = new Date(date);
        const options = { day: 'numeric', month: 'long', year: 'numeric' };
        const formattedDate = dateObj.toLocaleDateString('id-ID', options);
        document.getElementById('modalDate').textContent = formattedDate;

        let tasksHtml = '';

        if (!tasks || tasks.length === 0) {
            tasksHtml = `
                <div class="empty-plan text-center py-4">
                    <img src="https://cdni.iconscout.com/illustration/premium/thumb/empty-state-2130362-1800926.png" alt="Empty" style="width: 120px; opacity: 0.5;" class="mb-3">
                    <p class="text-muted mb-0">Tidak ada agenda tertulis.</p>
                </div>
            `;
        } else {
            tasks.forEach((task, index) => {
                const color = task.color || '#9ca3af';
                const categoryName = task.category_name || 'Kategori';
                const timeText = task.time || 'All Day';
                const isCompleted = task.status === 'selesai';
                const taskId = task.id || null;

                tasksHtml += `
                    <div class="task-item-modal-wrapper" style="border-left-color: ${color};">
                        <div class="d-flex align-items-start gap-3">
                            <!-- Checkbox -->
                            <div class="task-checkbox-wrapper">
                                <input type="checkbox" 
                                       class="form-check-input task-checkbox" 
                                       ${isCompleted ? 'checked' : ''} 
                                       ${taskId ? `data-task-id="${taskId}"` : 'disabled'}
                                       onclick="event.stopPropagation(); toggleTaskStatus(this, '${date}', ${index})"
                                       style="cursor: pointer; width: 20px; height: 20px;">
                            </div>
                            
                            <!-- Content -->
                            <div class="task-content-wrapper flex-grow-1">
                                <div class="d-flex justify-content-between align-items-start">
                                    <div>
                                        <h6 class="mb-1 fw-semibold ${isCompleted ? 'task-completed' : ''}">${task.title}</h6>
                                        <span class="badge rounded-pill category-badge" style="background-color: ${color}1A; color: ${color}; border: 1px solid ${color}33;">
                                            ${categoryName}
                                        </span>
                                    </div>
                                    <div class="task-time-edit-wrapper">
                                        <small class="text-muted task-time-text">
                                            <i class="bi bi-clock me-1"></i>${timeText}
                                        </small>
                                        <!-- Edit Button -->
                                        <button class="btn btn-sm btn-link text-muted task-edit-icon p-0 ms-2" 
                                                onclick="event.stopPropagation(); bukaModalEdit('${date}', ${index})"
                                                title="Edit tugas">
                                            <i class="bi bi-pencil"></i>
                                        </button>
                                        <!-- Delete Button (Grey/Muted as requested) -->
                                        <button class="btn btn-sm btn-link text-muted task-edit-icon p-0 ms-1" 
                                                onclick="event.stopPropagation(); konfirmasiHapusTugas('${taskId}', '${date}', ${index})"
                                                title="Hapus tugas">
                                            <i class="bi bi-trash"></i>
                                        </button>
                                    </div>
                                </div>
                                ${task.notes ? `<p class="text-muted small mb-0 mt-2">${task.notes}</p>` : ''}
                            </div>
                        </div>
                    </div>
                `;
            });
        }
        
        document.getElementById('taskDetailBody').innerHTML = tasksHtml;
    }

    // Main function to open modal
    function showTaskDetails(date, tasks) {
        renderTaskDetailList(date, tasks);
        // Use getOrCreateInstance to check existing state
        const modalEl = document.getElementById('taskDetailModal');
        const modal = bootstrap.Modal.getOrCreateInstance(modalEl);
        modal.show();
    }

    // ============================
    // 2. EDIT & ADD LOGIC
    // ============================

    function openAddTaskModal() {
        resetFormState();
        const modal = new bootstrap.Modal(document.getElementById('addTaskModal'));
        modal.show();
    }

    function openAddTaskModalWithDate(dateString) {
        // Tutup detail modal
        const detailModalEl = document.getElementById('taskDetailModal');
        const detailModalInstance = bootstrap.Modal.getInstance(detailModalEl);
        if (detailModalInstance) detailModalInstance.hide();

        // Reset form (ensure ADD mode)
        resetFormState();
        
        // Set tanggal otomatis dari tanggal yang diklik
        const dateParts = dateString.split('-');
        const newDate = new Date(dateParts[0], dateParts[1] - 1, dateParts[2]);
        selectedDate = newDate;
        currentDate = new Date(newDate);
        updateDateDisplay();
        renderModalCalendar();

        const modal = new bootstrap.Modal(document.getElementById('addTaskModal'));
        modal.show();
    }

    function bukaModalEdit(dateString, index) {
        const task = tasksData[dateString][index];
        if (!task) return;

        isEditing = true;
        editTargetDate = dateString;
        editTargetIndex = index;
        editTargetPlanId = task.id || null;

        document.getElementById('addTaskModal').classList.add('is-editing-mode');
        document.querySelector('#addTaskModalLabel i').className = 'bi bi-pencil-square-fill me-2';
        document.querySelector('#addTaskModalLabel i').style.color = '#f59e0b';
        document.getElementById('formTitleText').textContent = 'Ubah Rencana';
        document.getElementById('formSubtitleText').textContent = 'Edit detail tugas yang sudah ada';
        document.getElementById('btnText').textContent = 'Simpan Perubahan';
        document.querySelector('#submitTaskBtn i').className = 'bi bi-check-lg me-2';

        document.getElementById('taskTitle').value = task.title;
        document.getElementById('taskNotes').value = task.notes || '';
        
        const radios = document.getElementsByName('taskCategory');
        for(let r of radios) {
            if (String(r.value) === String(task.category_id)) r.checked = true;
        }

        const [y, m, d] = dateString.split('-').map(Number);
        selectedDate = new Date(y, m - 1, d);
        currentDate = new Date(y, m - 1, d);
        updateDateDisplay();
        renderModalCalendar();

        const timeStr = task.time; 
        if (timeStr && timeStr.includes('–')) {
            const parts = timeStr.split('–');
            document.getElementById('startTimeInput').value = parts[0].trim();
            document.getElementById('endTimeInput').value = parts[1].trim();
            document.getElementById('noSpecificTime').checked = false;
            document.getElementById('datetimeSection').classList.remove('disabled');
            document.getElementById('startTimeInput').disabled = false;
            document.getElementById('endTimeInput').disabled = false;
        } else {
            document.getElementById('noSpecificTime').checked = true;
            document.getElementById('startTimeInput').value = '';
            document.getElementById('endTimeInput').value = '';
            document.getElementById('datetimeSection').classList.add('disabled');
            document.getElementById('startTimeInput').disabled = true;
            document.getElementById('endTimeInput').disabled = true;
        }

        const detailModalEl = document.getElementById('taskDetailModal');
        const detailModalInstance = bootstrap.Modal.getInstance(detailModalEl);
        if (detailModalInstance) detailModalInstance.hide();

        const modal = new bootstrap.Modal(document.getElementById('addTaskModal'));
        modal.show();
    }

    function resetFormState() {
        isEditing = false;
        editTargetDate = null;
        editTargetIndex = null;
        editTargetPlanId = null;

        document.getElementById('addTaskModal').classList.remove('is-editing-mode');
        document.querySelector('#addTaskModalLabel i').className = 'bi bi-plus-circle-fill me-2';
        document.querySelector('#addTaskModalLabel i').style.color = '#10b981';
        document.getElementById('formTitleText').textContent = 'Rencana Baru';
        document.getElementById('formSubtitleText').textContent = 'Isi detail tugas kamu';
        document.getElementById('btnText').textContent = 'Tambah Tugas';
        document.querySelector('#submitTaskBtn i').className = 'bi bi-plus-circle me-2';

        document.getElementById('taskForm').reset();
        document.getElementById('taskForm').classList.remove('was-validated');
        document.getElementById('charCount').textContent = '0';

        selectedDate = new Date(); 
        currentDate = new Date();
        updateDateDisplay();
        renderModalCalendar();
        
        document.getElementById('startTimeInput').value = "7:30pm";
        document.getElementById('endTimeInput').value = "8:30pm";
        document.getElementById('datetimeSection').classList.remove('disabled');
        document.getElementById('startTimeInput').disabled = false;
        document.getElementById('endTimeInput').disabled = false;
    }

    function saveTask() {
        const form = document.getElementById('taskForm');
        if (!form.checkValidity()) { 
            form.classList.add('was-validated'); 
            return; 
        }
        
        const isNoTime = document.getElementById('noSpecificTime').checked;
        
        const year = selectedDate.getFullYear();
        const month = String(selectedDate.getMonth() + 1).padStart(2, '0');
        const day = String(selectedDate.getDate()).padStart(2, '0');
        const formattedDate = `${year}-${month}-${day}`;
        
        const startTime = document.getElementById('startTimeInput').value;
        const endTime = document.getElementById('endTimeInput').value;
        const formattedTime = isNoTime ? null : `${startTime} – ${endTime}`;

        const kategoriInput = document.querySelector('input[name="taskCategory"]:checked');
        const kategoriId = kategoriInput ? kategoriInput.value : null;

        const payload = {
            judul_tugas: document.getElementById('taskTitle').value,
            kategori_id: kategoriId,
            tanggal: formattedDate,
            waktu: formattedTime,
            catatan: document.getElementById('taskNotes').value
        };

        const modalEl = document.getElementById('addTaskModal');
        const modal = bootstrap.Modal.getInstance(modalEl);

        const csrfTokenMeta = document.querySelector('meta[name="csrf-token"]');
        const csrfToken = csrfTokenMeta ? csrfTokenMeta.getAttribute('content') : '';

        createCategoryIfNeeded(csrfToken)
            .then(newKategoriId => {
                const kategoriIdToUse = newKategoriId || payload.kategori_id;
                const finalPayload = { ...payload, kategori_id: kategoriIdToUse };

                if (isEditing && editTargetPlanId) {
                    return fetch(`/rencana/${editTargetPlanId}`, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'Accept': 'application/json',
                            'X-CSRF-TOKEN': csrfToken,
                        },
                        body: JSON.stringify(finalPayload),
                    });
                }

                return fetch("{{ route('rencana.store') }}", {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Accept': 'application/json',
                        'X-CSRF-TOKEN': csrfToken,
                    },
                    body: JSON.stringify(finalPayload),
                });
            })
            .then(response => {
                if (!response || !response.ok) throw new Error('Gagal menyimpan');
                return response.json().catch(() => ({}));
            })
            .then(() => {
                if (modal) modal.hide();
                form.reset();
                form.classList.remove('was-validated');
                document.getElementById('charCount').textContent = '0';

                const toast = new bootstrap.Toast(document.getElementById('successToast'));
                toast.show();

                setTimeout(() => {
                    window.location.reload();
                }, 600);
            })
            .catch(() => {
                if (window.showToast) {
                    window.showToast('Gagal menyimpan rencana. Silakan coba lagi.', 'error');
                }
            });
    }

    // ============================
    // 3. WIDGET LOGIC (DATE & TIME)
    // ============================
    
    const dateDisplayBox = document.getElementById('dateDisplayBox');
    const dateText = document.getElementById('dateText');
    const calendarPopup = document.getElementById('calendarPopup');
    const calendarTitle = document.getElementById('calendarTitle');
    const modalCalendarGrid = document.getElementById('modalCalendarGrid');
    
    let currentDate = new Date();
    let selectedDate = new Date();

    const startTimeInput = document.getElementById('startTimeInput');
    const endTimeInput = document.getElementById('endTimeInput');
    const startTimeDropdown = document.getElementById('startTimeDropdown');
    const endTimeDropdown = document.getElementById('endTimeDropdown');

    function setupModalFormLogic() {
        document.getElementById('taskForm').addEventListener('submit', function(event) {
            event.preventDefault();
            saveTask();
        });
        
        document.getElementById('taskNotes').addEventListener('input', function() {
            document.getElementById('charCount').textContent = this.value.length;
        });
        
        document.getElementById('noSpecificTime').addEventListener('change', function() {
            const wrapper = document.getElementById('datetimeSection');
            const timeInputs = document.querySelectorAll('#startTimeInput, #endTimeInput');
            if (this.checked) {
                wrapper.classList.add('disabled');
                timeInputs.forEach(input => { input.value = ''; input.disabled = true; });
            } else {
                wrapper.classList.remove('disabled');
                timeInputs.forEach(input => {
                    input.value = (input.id === 'startTimeInput' ? '7:30pm' : '8:30pm');
                    input.disabled = false;
                });
            }
        });

        dateDisplayBox.addEventListener('click', (e) => {
            e.stopPropagation();
            if (document.getElementById('datetimeSection').classList.contains('disabled')) return;
            const isOpen = calendarPopup.classList.contains('show');
            closeAllPopups();
            if (!isOpen) {
                calendarPopup.classList.add('show');
                dateDisplayBox.classList.add('active');
                renderModalCalendar();
            }
        });

        document.getElementById('prevMonth').addEventListener('click', (e) => { e.stopPropagation(); currentDate.setMonth(currentDate.getMonth() - 1); renderModalCalendar(); });
        document.getElementById('nextMonth').addEventListener('click', (e) => { e.stopPropagation(); currentDate.setMonth(currentDate.getMonth() + 1); renderModalCalendar(); });

        setupTimePicker('startTimeInput', 'startTimeDropdown');
        setupTimePicker('endTimeInput', 'endTimeDropdown');

        window.addEventListener('click', closeAllPopups);
        calendarPopup.addEventListener('click', (e) => e.stopPropagation());
        startTimeDropdown.addEventListener('click', (e) => e.stopPropagation());
        endTimeDropdown.addEventListener('click', (e) => e.stopPropagation());

        updateDateDisplay();
    }

    function renderModalCalendar() {
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();
        const monthNamesId = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"];
        calendarTitle.textContent = `${monthNamesId[month]} ${year}`;
        
        const headers = (weekStart === 1) ? ['Sen','Sel','Rab','Kam','Jum','Sab','Min'] : ['Min','Sen','Sel','Rab','Kam','Jum','Sab'];
        modalCalendarGrid.innerHTML = headers.map(h => `<div class="calendar-day-label">${h}</div>`).join('');
        
        const firstDayIndexRaw = new Date(year, month, 1).getDay();
        const firstDayIndex = (firstDayIndexRaw - weekStart + 7) % 7;
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const today = new Date();
        
        // Previous Month
        for (let i = 0; i < firstDayIndex; i++) {
            const emptyDiv = document.createElement('div');
            emptyDiv.className = 'calendar-day empty';
            modalCalendarGrid.appendChild(emptyDiv);
        }

        // Current Month
        for (let i = 1; i <= daysInMonth; i++) {
            const dayEl = document.createElement('div');
            dayEl.className = 'calendar-day';
            dayEl.textContent = i;
            if (i === selectedDate.getDate() && month === selectedDate.getMonth() && year === selectedDate.getFullYear()) dayEl.classList.add('selected');
            if (i === today.getDate() && month === today.getMonth() && year === today.getFullYear()) dayEl.classList.add('today');
            dayEl.addEventListener('click', (e) => {
                e.stopPropagation();
                selectedDate = new Date(year, month, i);
                updateDateDisplay();
                calendarPopup.classList.remove('show');
                dateDisplayBox.classList.remove('active');
            });
            modalCalendarGrid.appendChild(dayEl);
        }
    }

    function updateDateDisplay() {
        const options = { weekday: 'long', month: 'long', day: 'numeric' };
        dateText.textContent = selectedDate.toLocaleDateString('id-ID', options);
    }

    function generateTimeOptions() {
        const times = [];
        for (let i = 0; i < 24; i++) {
            for (let j = 0; j < 60; j += 15) {
                const hour = i; const minute = j;
                const period = hour >= 12 ? 'pm' : 'am';
                const displayHour = hour % 12 || 12;
                const displayMinute = minute < 10 ? '0' + minute : minute;
                times.push(`${displayHour}:${displayMinute}${period}`);
            }
        }
        return times;
    }
    const timeOptions = generateTimeOptions();

    function setupTimePicker(inputId, dropdownId) {
        const input = document.getElementById(inputId);
        const dropdown = document.getElementById(dropdownId);
        populateDropdown(dropdown, timeOptions, input);

        input.addEventListener('focus', (e) => {
            e.stopPropagation();
            if (document.getElementById('datetimeSection').classList.contains('disabled')) return;
            document.querySelectorAll('.time-dropdown').forEach(d => { if(d !== dropdown) d.classList.remove('show'); });
            dropdown.classList.add('show');
            input.parentElement.classList.add('active');
            filterDropdown(input.value, dropdown);
        });

        input.addEventListener('input', (e) => { filterDropdown(e.target.value, dropdown); });
        
        input.addEventListener('keydown', (e) => {
            const highlighted = dropdown.querySelector('.time-option.highlighted');
            if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
                e.preventDefault();
                const options = Array.from(dropdown.querySelectorAll('.time-option:not([style*="display: none"])'));
                let currentIndex = options.indexOf(highlighted);
                if (e.key === 'ArrowDown') currentIndex = (currentIndex + 1) % options.length;
                if (e.key === 'ArrowUp') currentIndex = (currentIndex - 1 + options.length) % options.length;
                options.forEach(opt => opt.classList.remove('highlighted'));
                if(options[currentIndex]) {
                    options[currentIndex].classList.add('highlighted');
                    options[currentIndex].scrollIntoView({ block: 'nearest' });
                }
            } else if (e.key === 'Enter') {
                e.preventDefault();
                if (highlighted) { input.value = highlighted.textContent; dropdown.classList.remove('show'); } 
                else { dropdown.classList.remove('show'); }
            }
        });

        dropdown.addEventListener('click', (e) => {
            if (e.target.classList.contains('time-option')) {
                input.value = e.target.textContent;
                dropdown.classList.remove('show');
            }
        });
    }

    function populateDropdown(dropdown, options, input) {
        dropdown.innerHTML = '';
        options.forEach(time => {
            const div = document.createElement('div');
            div.className = 'time-option';
            div.textContent = time;
            if (time === input.value) div.classList.add('highlighted');
            div.addEventListener('mouseover', function() {
                dropdown.querySelectorAll('.time-option').forEach(el => el.classList.remove('highlighted'));
                this.classList.add('highlighted');
            });
            dropdown.appendChild(div);
        });
    }

    function filterDropdown(query, dropdown) {
        const options = dropdown.querySelectorAll('.time-option');
        const lowerQuery = query.toLowerCase();
        let firstVisible = null;
        options.forEach(opt => {
            const text = opt.textContent.toLowerCase();
            if (text.includes(lowerQuery)) {
                opt.style.display = 'block';
                if (!firstVisible) firstVisible = opt;
            } else { opt.style.display = 'none'; }
            opt.classList.remove('highlighted');
        });
        if (firstVisible) { firstVisible.classList.add('highlighted'); firstVisible.scrollIntoView({ block: 'nearest' }); }
    }

    function closeAllPopups() {
        calendarPopup.classList.remove('show');
        dateDisplayBox.classList.remove('active');
        document.querySelectorAll('.time-dropdown').forEach(d => d.classList.remove('show'));
        document.querySelectorAll('.time-input-group').forEach(g => g.classList.remove('active'));
    }

    // ============================
    // 4. CUSTOM CATEGORY LOGIC
    // ============================
    function resolveCategoryPillStyle(rawColor) {
        const lower = String(rawColor || '').trim().toLowerCase();
        const map = {
            'biru': { bg: '#dbeafe', text: '#1e40af' },
            'blue': { bg: '#dbeafe', text: '#1e40af' },
            'hijau': { bg: '#d1fae5', text: '#065f46' },
            'green': { bg: '#d1fae5', text: '#065f46' },
            'kuning': { bg: '#fef3c7', text: '#92400e' },
            'yellow': { bg: '#fef3c7', text: '#92400e' },
            'merah': { bg: '#fee2e2', text: '#991b1b' },
            'red': { bg: '#fee2e2', text: '#991b1b' },
            'ungu': { bg: '#ede9fe', text: '#5b21b6' },
            'purple': { bg: '#ede9fe', text: '#5b21b6' },
            'pink': { bg: '#fce7f3', text: '#9d174d' },
            'abu-abu': { bg: '#f3f4f6', text: '#374151' },
            'gray': { bg: '#f3f4f6', text: '#374151' },
            'grey': { bg: '#f3f4f6', text: '#374151' },
        };
        const darkMap = {
            'biru': { bg: 'rgba(37, 99, 235, 0.15)', text: '#93c5fd', border: 'rgba(59, 130, 246, 0.3)' },
            'blue': { bg: 'rgba(37, 99, 235, 0.15)', text: '#93c5fd', border: 'rgba(59, 130, 246, 0.3)' },
            'hijau': { bg: 'rgba(16, 185, 129, 0.15)', text: '#6ee7b7', border: 'rgba(16, 185, 129, 0.3)' },
            'green': { bg: 'rgba(16, 185, 129, 0.15)', text: '#6ee7b7', border: 'rgba(16, 185, 129, 0.3)' },
            'kuning': { bg: 'rgba(245, 158, 11, 0.15)', text: '#fcd34d', border: 'rgba(245, 158, 11, 0.3)' },
            'yellow': { bg: 'rgba(245, 158, 11, 0.15)', text: '#fcd34d', border: 'rgba(245, 158, 11, 0.3)' },
            'merah': { bg: 'rgba(239, 68, 68, 0.15)', text: '#fca5a5', border: 'rgba(239, 68, 68, 0.3)' },
            'red': { bg: 'rgba(239, 68, 68, 0.15)', text: '#fca5a5', border: 'rgba(239, 68, 68, 0.3)' },
            'ungu': { bg: 'rgba(124, 58, 237, 0.15)', text: '#ddd6fe', border: 'rgba(124, 58, 237, 0.3)' },
            'purple': { bg: 'rgba(124, 58, 237, 0.15)', text: '#ddd6fe', border: 'rgba(124, 58, 237, 0.3)' },
            'pink': { bg: 'rgba(236, 72, 153, 0.15)', text: '#fbcfe8', border: 'rgba(236, 72, 153, 0.3)' },
            'abu-abu': { bg: 'rgba(156, 163, 175, 0.15)', text: '#e5e7eb', border: 'rgba(156, 163, 175, 0.3)' },
            'gray': { bg: 'rgba(156, 163, 175, 0.15)', text: '#e5e7eb', border: 'rgba(156, 163, 175, 0.3)' },
            'grey': { bg: 'rgba(156, 163, 175, 0.15)', text: '#e5e7eb', border: 'rgba(156, 163, 175, 0.3)' },
        };
        const base = map[lower] || { bg: '#f3f4f6', text: '#374151' };
        const dark = darkMap[lower] || { bg: 'rgba(156, 163, 175, 0.15)', text: '#e5e7eb', border: 'rgba(156, 163, 175, 0.3)' };
        return { ...base, darkBg: dark.bg, darkText: dark.text, darkBorder: dark.border };
    }


    function addCategoryOptionToHome(category) {
        const additional = document.getElementById('additionalCategories');
        if (!additional) return;
        const categoryId = 'categoryDb_' + category.kategori_id;
        const style = resolveCategoryPillStyle(category.warna);
        const newCategory = document.createElement('div');
        newCategory.innerHTML = `<input type="radio" class="btn-check" name="taskCategory" id="${categoryId}" value="${category.kategori_id}" autocomplete="off"><label class="btn btn-sm btn-category" for="${categoryId}" style="--pill-bg: ${style.bg}; --pill-text: ${style.text}; --pill-bg-dark: ${style.darkBg}; --pill-text-dark: ${style.darkText}; --pill-border-dark: ${style.darkBorder};"><i class="bi bi-tag me-1"></i>${category.nama_kategori}</label>`;
        additional.appendChild(newCategory);
    }

    
    function addNewCategory() {
        const categoryName = document.getElementById('newCategoryName').value.trim();
        if (!categoryName) {
            if (window.showToast) window.showToast('Mohon isi nama kategori.', 'error');
            return;
        }

        const warna = (document.getElementById('newCategoryColor')?.value || '').trim();

        const csrfTokenMeta = document.querySelector('meta[name="csrf-token"]');
        const csrfToken = csrfTokenMeta ? csrfTokenMeta.getAttribute('content') : '';

        fetch("{{ route('categories.store') }}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
                'X-CSRF-TOKEN': csrfToken,
            },
            body: JSON.stringify({ nama_kategori: categoryName, warna }),
        })
            .then(response => {
                if (!response.ok) throw new Error('Gagal menyimpan kategori');
                return response.json();
            })
            .then(data => {
                if (!data || !data.success || !data.category) throw new Error('Response tidak valid');

                const hint = document.getElementById('emptyCategoryHint');
                if (hint) hint.remove();

                addCategoryOptionToHome(data.category);

                const newInputId = 'categoryDb_' + data.category.kategori_id;
                const newRadio = document.getElementById(newInputId);
                if (newRadio) newRadio.checked = true;

                document.getElementById('newCategoryName').value = '';
                const colorEl = document.getElementById('newCategoryColor');
                if (colorEl) colorEl.value = 'biru';
                document.getElementById('addCategoryForm').classList.add('d-none');
            })
            .catch(() => {
                if (window.showToast) window.showToast('Gagal menambahkan kategori. Silakan coba lagi.', 'error');
            });
    }

    function cancelAddCategory() {
        document.getElementById('newCategoryName').value = '';
        const colorEl = document.getElementById('newCategoryColor');
        if (colorEl) colorEl.value = 'biru';
        document.getElementById('addCategoryForm').classList.add('d-none');
    }

    function createCategoryIfNeeded(csrfToken) {
        const addCategoryForm = document.getElementById('addCategoryForm');
        const isFormVisible = addCategoryForm && !addCategoryForm.classList.contains('d-none');
        if (!isFormVisible) return Promise.resolve(null);

        const categoryName = document.getElementById('newCategoryName')?.value?.trim() || '';
        const warna = (document.getElementById('newCategoryColor')?.value || '').trim();
        if (!categoryName) return Promise.resolve(null);

        return fetch("{{ route('categories.store') }}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
                'X-CSRF-TOKEN': csrfToken,
            },
            body: JSON.stringify({ nama_kategori: categoryName, warna }),
        })
            .then(response => {
                if (!response.ok) throw new Error('Gagal menyimpan kategori');
                return response.json();
            })
            .then(data => {
                if (!data || !data.success || !data.category) throw new Error('Response tidak valid');

                const hint = document.getElementById('emptyCategoryHint');
                if (hint) hint.remove();

                addCategoryOptionToHome(data.category);
                const newInputId = 'categoryDb_' + data.category.kategori_id;
                const newRadio = document.getElementById(newInputId);
                if (newRadio) newRadio.checked = true;

                document.getElementById('newCategoryName').value = '';
                const colorEl = document.getElementById('newCategoryColor');
                if (colorEl) colorEl.value = 'biru';
                document.getElementById('addCategoryForm').classList.add('d-none');

                return data.category.kategori_id;
            });
    }

    // ============================
    // 5. TOGGLE STATUS FUNCTION
    // ============================
    function toggleTaskStatus(checkbox, date, index) {
        const taskId = checkbox.getAttribute('data-task-id');
        if (!taskId) {
            if (window.showToast) window.showToast('Tugas ini belum tersimpan di database.', 'error');
            checkbox.checked = !checkbox.checked; // Revert
            return;
        }

        const newStatus = checkbox.checked ? 'selesai' : null;
        const csrfTokenMeta = document.querySelector('meta[name="csrf-token"]');
        const csrfToken = csrfTokenMeta ? csrfTokenMeta.getAttribute('content') : '';

        // Update UI immediately for better UX
        const taskItem = checkbox.closest('.task-item-modal-wrapper');
        const titleElement = taskItem.querySelector('h6');
        if (checkbox.checked) {
            titleElement.classList.add('task-completed');
        } else {
            titleElement.classList.remove('task-completed');
        }

        // Update database
        fetch(`/rencana/${taskId}/toggle-status`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
                'X-CSRF-TOKEN': csrfToken,
            },
            body: JSON.stringify({ status: newStatus }),
        })
            .then(response => {
                if (!response.ok) throw new Error('Gagal mengubah status');
                return response.json();
            })
            .then(() => {
                // Update local tasksData
                if (tasksData[date] && tasksData[date][index]) {
                    tasksData[date][index].status = newStatus;
                }
                
                // Update stats
                updateStats();
                
                // Dispatch event untuk update sidebar stats
                window.dispatchEvent(new Event('storage'));
            })
            .catch(error => {
                console.error('Error:', error);
                if (window.showToast) window.showToast('Gagal mengubah status tugas. Silakan coba lagi.', 'error');
                
                // Revert UI on error
                checkbox.checked = !checkbox.checked;
                if (checkbox.checked) {
                    titleElement.classList.add('task-completed');
                } else {
                    titleElement.classList.remove('task-completed');
                }
            });
    }

    // ============================
    // 6. DELETE TASK LOGIC (UPDATED)
    // ============================
    
    // ============================
    // 6. DELETE TASK LOGIC (FIXED)
    // ============================
    
    let taskToDelete = null; 

    function konfirmasiHapusTugas(taskId, date, index) {
        taskToDelete = { taskId, date, index };
        const el = document.getElementById('deleteConfirmationModal');
        const modal = bootstrap.Modal.getOrCreateInstance(el);
        // Ensure z-index is higher than taskDetailModal if needed, but Bootstrap handles stacking usually.
        modal.show();
    }

    // Attach listener for the delete button
    // We use a self-executing function or just place it here to run when script executes
    (function setupDeleteListener() {
        const btn = document.getElementById('confirmDeleteBtn');
        if (btn) {
            // Remove old listener if any to avoid duplicates (clone node trick or just assume unique)
            const newBtn = btn.cloneNode(true);
            btn.parentNode.replaceChild(newBtn, btn);
            
            newBtn.addEventListener('click', () => {
                if (taskToDelete) {
                    prosesHapusTugas(taskToDelete.taskId, taskToDelete.date, taskToDelete.index);
                    const el = document.getElementById('deleteConfirmationModal');
                    const modal = bootstrap.Modal.getInstance(el);
                    if (modal) modal.hide();
                }
            });
        }
    })();

    function prosesHapusTugas(taskId, date, index) {
        const csrfTokenMeta = document.querySelector('meta[name="csrf-token"]');
        const csrfToken = csrfTokenMeta ? csrfTokenMeta.getAttribute('content') : '';

        fetch(`/rencana/${taskId}/delete`, {
            method: 'DELETE',
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
                'X-CSRF-TOKEN': csrfToken,
            },
        })
            .then(response => {
                if (!response.ok) throw new Error('Gagal menghapus rencana');
                return response.json();
            })
            .then(() => {
                // 1. Update data lokal
                const currentTasks = tasksData[date];
                if (currentTasks) {
                    currentTasks.splice(index, 1);
                    // 2. Update tampilan List (tanpa re-open modal)
                    renderTaskDetailList(date, currentTasks);
                }

                // 3. Notifikasi Toast
                if (typeof showToast === 'function') {
                    showToast('Rencana berhasil dihapus.', 'success');
                } else if (window.showToast) {
                    window.showToast('Rencana berhasil dihapus.', 'success');
                } else {
                    // Fallback manual toast trigger
                    const toastEl = document.getElementById('successToast');
                    if (toastEl) {
                        const toast = new bootstrap.Toast(toastEl);
                        toast.show();
                    }
                }

                // 4. Update Stats & Calendar Dots
                updateStats();
                renderCalendar();
                window.dispatchEvent(new Event('storage'));
            })
            .catch(error => {
                console.error(error);
                if (window.showToast) window.showToast('Gagal menghapus rencana.', 'error');
            });
    }
</script>
@endpush