@extends('layouts.app')

@section('title', 'Kalender - FocusDay')

@section('content')
<div class="container-fluid">
    <!-- Header Section -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h2 class="fw-bold text-dark mb-1">Kalender Rencana</h2>
                    <p class="text-muted mb-0">Lihat semua rencana Anda dalam sebulan</p>
                </div>
                <!-- Tombol Buka Form -->
                <button class="btn btn-success btn-add-task shadow-sm" data-bs-toggle="modal" data-bs-target="#addTaskModal" onclick="resetFormState()">
                    <i class="bi bi-plus-circle me-2"></i>Tambah Rencana
                </button>
            </div>
        </div>
    </div>
    
    <div class="row">
        <!-- Calendar Section -->
        <div class="col-lg-9 mb-4">
            <div class="card border-0 shadow-sm">
                <div class="card-body p-4">
                    <!-- Month Navigation -->
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <button class="btn btn-light" id="prevMonthBtn">
                            <i class="bi bi-chevron-left"></i>
                        </button>
                        <h4 class="fw-bold mb-0" id="monthLabel">Januari 2026</h4>
                        <button class="btn btn-light" id="nextMonthBtn">
                            <i class="bi bi-chevron-right"></i>
                        </button>
                    </div>
                    
                    <!-- Calendar Grid -->
                    <div class="calendar-grid" id="mainCalendarGrid">
                        <!-- Headers Statis -->
                        <div class="calendar-day-header">Min</div>
                        <div class="calendar-day-header">Sen</div>
                        <div class="calendar-day-header">Sel</div>
                        <div class="calendar-day-header">Rab</div>
                        <div class="calendar-day-header">Kam</div>
                        <div class="calendar-day-header">Jum</div>
                        <div class="calendar-day-header">Sab</div>
                        
                        <!-- Days generated by JS -->
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Sidebar Legend -->
        <div class="col-lg-3">
            <div class="card border-0 shadow-sm mb-4">
                <div class="card-body p-4">
                    <h5 class="fw-semibold mb-3">
                        <i class="bi bi-palette me-2"></i>
                        Kategori
                    </h5>
                    
                    <div class="category-legend">
                        <div class="legend-item">
                            <span class="legend-dot task-dot-work"></span>
                            <span class="legend-label">Kerja</span>
                        </div>
                        <div class="legend-item">
                            <span class="legend-dot task-dot-learning"></span>
                            <span class="legend-label">Belajar</span>
                        </div>
                        <div class="legend-item">
                            <span class="legend-dot task-dot-personal"></span>
                            <span class="legend-label">Pribadi</span>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Quick Stats -->
            <div class="card border-0 shadow-sm quick-stats-card">
                <div class="card-body p-4">
                    <h5 class="fw-semibold mb-3">
                        <i class="bi bi-graph-up me-2 text-success"></i>
                        Statistik Bulan Ini
                    </h5>
                    
                    <div class="stat-item mb-3">
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="text-muted">Total Tugas</span>
                            <span class="fw-bold text-dark" id="statTotal">0</span>
                        </div>
                    </div>
                    
                    <div class="stat-item mb-3">
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="text-muted">Selesai</span>
                            <span class="fw-bold text-success">18</span>
                        </div>
                    </div>
                    
                    <div class="stat-item">
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="text-muted">Tertunda</span>
                            <span class="fw-bold text-warning">6</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Task Detail Modal -->
<div class="modal fade" id="taskDetailModal" tabindex="-1" aria-labelledby="taskDetailModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-0 shadow">
            <div class="modal-header border-0">
                <h5 class="modal-title fw-bold" id="taskDetailModalLabel">Rencana - <span id="modalDate"></span></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="taskDetailBody">
                <!-- Tasks populated via JS -->
            </div>
            <!-- Modal Footer -->
            <div class="modal-footer border-0">
                <!-- Tombol Tambah Rencana (Always Available) -->
                <button type="button" class="btn btn-success" onclick="openAddTaskModalWithDate(selectedCalendarDateString)">
                    <i class="bi bi-plus-circle me-2"></i>Tambah Rencana
                </button>
                <!-- Tombol Tutup -->
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Tutup</button>
            </div>
        </div>
    </div>
</div>

<!-- ADD/EDIT TASK MODAL -->
<div class="modal fade" id="addTaskModal" tabindex="-1" aria-labelledby="addTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-0 shadow-lg">
            <!-- Modal Header -->
            <div class="modal-header border-0 pb-3" style="border-bottom: 1px solid #e5e7eb !important;">
                <div class="w-100 d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="modal-title fw-bold text-dark mb-0" id="addTaskModalLabel">
                            <i class="bi bi-plus-circle-fill me-2" style="color: #10b981;"></i>
                            <span id="formTitleText">Rencana Baru</span>
                        </h5>
                        <small class="text-muted" id="formSubtitleText">Isi detail tugas kamu</small>
                    </div>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="resetFormState()"></button>
                </div>
            </div>
            
            <div class="modal-body p-4 pt-3">
                <form id="taskForm" class="needs-validation" novalidate>
                    <!-- Judul Tugas -->
                    <div class="mb-4">
                        <label for="taskTitle" class="form-label fw-semibold text-dark">
                            <i class="bi bi-card-heading me-1 text-muted" style="font-size: 0.9rem;"></i>
                            Judul Tugas
                        </label>
                        <input type="text" 
                               class="form-control form-control-lg" 
                               id="taskTitle" 
                               placeholder="Contoh: Meeting dengan tim development" 
                               required
                               style="border-radius: 10px; border: 2px solid #e5e7eb; padding: 0.75rem 1rem;">
                        <div class="invalid-feedback">Harap isi judul tugas</div>
                    </div>
                    
                    <!-- Kategori -->
                    <div class="mb-4">
                        <label class="form-label fw-semibold text-dark d-flex justify-content-between align-items-center">
                            <span>
                                <i class="bi bi-tag me-1 text-muted" style="font-size: 0.9rem;"></i>
                                Kategori
                            </span>
                            <button type="button" class="btn btn-sm btn-outline-secondary border-0 p-0" 
                                    style="font-size: 0.8rem;" onclick="showAddCategory()">
                                <i class="bi bi-plus-circle me-1"></i>Tambah Kategori
                            </button>
                        </label>
                        <div class="d-flex flex-wrap gap-2" id="categorySelection">
                            <!-- Default Categories -->
                            <input type="radio" class="btn-check" name="taskCategory" id="categoryWork" value="work" autocomplete="off" checked>
                            <label class="btn btn-sm btn-category btn-work" for="categoryWork">
                                <i class="bi bi-briefcase me-1"></i>Kerja
                            </label>
                            
                            <input type="radio" class="btn-check" name="taskCategory" id="categoryLearning" value="learning" autocomplete="off">
                            <label class="btn btn-sm btn-category btn-learning" for="categoryLearning">
                                <i class="bi bi-book me-1"></i>Belajar
                            </label>
                            
                            <input type="radio" class="btn-check" name="taskCategory" id="categoryPersonal" value="personal" autocomplete="off">
                            <label class="btn btn-sm btn-category btn-personal" for="categoryPersonal">
                                <i class="bi bi-person me-1"></i>Pribadi
                            </label>
                            
                            <!-- Dynamic Categories Container -->
                            <div id="additionalCategories"></div>
                        </div>
                    </div>
                    
                    <!-- WIDGET TANGGAL & WAKTU -->
                    <div class="mb-4" id="datetimeSection">
                        <label class="form-label fw-semibold text-dark mb-3">
                            <i class="bi bi-clock me-1 text-muted" style="font-size: 0.9rem;"></i>
                            Tanggal & Waktu
                        </label>
                        
                        <div class="datetime-wrapper">
                            <!-- BAGIAN TANGGAL -->
                            <div class="date-section" id="dateWidget">
                                <div class="custom-input-box" id="dateDisplayBox">
                                    <span class="date-display-text" id="dateText">Thursday, January 8</span>
                                    <!-- CALENDAR POPUP -->
                                    <div class="calendar-popup" id="calendarPopup">
                                        <div class="calendar-header">
                                            <button type="button" class="calendar-nav-btn" id="prevMonth">&lt;</button>
                                            <span class="calendar-month-title" id="calendarTitle">January 2026</span>
                                            <button type="button" class="calendar-nav-btn" id="nextMonth">&gt;</button>
                                        </div>
                                        <div class="calendar-grid" id="modalCalendarGrid">
                                            <!-- JS generated -->
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- BAGIAN WAKTU -->
                            <div class="time-section">
                                <div class="custom-input-box" id="timeDisplayBox">
                                    <div class="time-input-group" id="startTimeGroup">
                                        <input type="text" id="startTimeInput" value="7:30pm" placeholder="Start" autocomplete="off">
                                        <div class="time-dropdown" id="startTimeDropdown"></div>
                                    </div>
                                    <span class="time-separator">–</span>
                                    <div class="time-input-group" id="endTimeGroup">
                                        <input type="text" id="endTimeInput" value="8:30pm" placeholder="End" autocomplete="off">
                                        <div class="time-dropdown" id="endTimeDropdown"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-check form-check-inline mt-2" style="margin-left: 5px;">
                            <input class="form-check-input" type="checkbox" id="noSpecificTime">
                            <label class="form-check-label text-muted" for="noSpecificTime" style="font-size: 0.85rem;">
                                Tanpa waktu spesifik
                            </label>
                        </div>
                    </div>
                    
                    <!-- Catatan -->
                    <div class="mb-3">
                        <label for="taskNotes" class="form-label fw-semibold text-dark">
                            <i class="bi bi-sticky me-1 text-muted" style="font-size: 0.9rem;"></i>
                            Catatan <span class="text-muted fw-normal">(Opsional)</span>
                        </label>
                        <textarea class="form-control" 
                                  id="taskNotes" 
                                  rows="2" 
                                  placeholder="Tambahkan detail, link, atau catatan penting..."
                                  style="border-radius: 10px; border: 2px solid #e5e7eb; resize: none;"></textarea>
                        <div class="d-flex justify-content-between mt-1">
                            <small class="text-muted" style="font-size: 0.75rem;">
                                <i class="bi bi-info-circle me-1"></i>
                                Kosongkan waktu untuk tugas tanpa deadline spesifik
                            </small>
                            <small class="text-muted char-count" style="font-size: 0.75rem;">
                                <span id="charCount">0</span>/300
                            </small>
                        </div>
                    </div>
                </form>
                
                <!-- Form tambah kategori -->
                <div class="border-top mt-4 pt-3 d-none" id="addCategoryForm">
                    <label class="form-label fw-semibold text-dark mb-2">
                        <i class="bi bi-plus-circle me-1 text-success"></i>
                        Tambah Kategori Baru
                    </label>
                    <div class="input-group input-group-sm">
                        <input type="text" 
                               class="form-control" 
                               id="newCategoryName" 
                               placeholder="Nama kategori baru"
                               style="border-radius: 8px 0 0 8px;">
                        <button class="btn btn-outline-success" type="button" onclick="addNewCategory()" style="border-radius: 0 8px 8px 0;">
                            <i class="bi bi-check-lg"></i>
                        </button>
                    </div>
                </div>
            </div>
            
            <!-- Modal Footer -->
            <div class="modal-footer border-0 pt-0">
                <button type="button" class="btn btn-light btn-lg px-4" data-bs-dismiss="modal" onclick="resetFormState()" style="border-radius: 10px;">
                    Batal
                </button>
                <button type="button" class="btn btn-success btn-lg px-4" onclick="saveTask()" id="submitTaskBtn" style="border-radius: 10px;">
                    <i class="bi bi-plus-circle me-2"></i><span id="btnText">Tambah Tugas</span>
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Toast Notification -->
<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
    <div id="successToast" class="toast align-items-center text-white bg-success border-0 shadow" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body d-flex align-items-center">
                <i class="bi bi-check-circle-fill me-2" style="font-size: 1.2rem;"></i>
                <div>
                    <strong id="toastMessage">Rencana berhasil disimpan!</strong>
                    <div class="small" id="toastSubMessage">Tugas telah masuk ke kalender</div>
                </div>
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

@endsection

@push('styles')
<style>
    /* =========================================
       1. ORIGINAL CALENDAR PAGE STYLES
       ========================================= */
    
    .quick-stats-card {
        background: linear-gradient(135deg, #f0fdf4 0%, #ffffff 100%);
    }

    html[data-theme="dark"] .quick-stats-card {
        background: linear-gradient(135deg, rgba(16, 185, 129, 0.12) 0%, rgba(15, 23, 42, 0.75) 100%);
    }

    .calendar-grid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 8px;
    }
    
    .calendar-day-header {
        text-align: center;
        font-weight: 600;
        color: #6b7280;
        padding: 0.75rem 0;
        font-size: 0.875rem;
    }

    html[data-theme="dark"] .calendar-day-header {
        color: #94a3b8;
    }
    
    .calendar-day {
        aspect-ratio: 1;
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 0.5rem;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: flex-start;
        cursor: pointer;
        transition: all 0.2s ease;
        background-color: #ffffff;
        position: relative;
    }

    html[data-theme="dark"] .calendar-day {
        border-color: #1f2937;
        background-color: rgba(15, 23, 42, 0.85);
    }
    
    .calendar-day:hover {
        border-color: var(--primary-green);
        background-color: #f0fdf4;
        transform: scale(1.05);
        box-shadow: 0 2px 8px rgba(16, 185, 129, 0.15);
    }

    html[data-theme="dark"] .calendar-day:hover {
        background-color: rgba(16, 185, 129, 0.08);
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.35);
    }
    
    .calendar-day.today {
        background: linear-gradient(135deg, var(--primary-green-light), #ffffff);
        border: 2px solid var(--primary-green);
    }

    html[data-theme="dark"] .calendar-day.today {
        background: linear-gradient(135deg, rgba(16, 185, 129, 0.18), rgba(15, 23, 42, 0.85));
        border: 2px solid var(--primary-green);
    }
    
    .calendar-day.today .day-number {
        color: var(--primary-green-dark);
        font-weight: 700;
    }

    html[data-theme="dark"] .calendar-day.today .day-number {
        color: var(--primary-green);
    }
    
    .calendar-day.other-month {
        background-color: #f9fafb;
        color: #d1d5db;
        cursor: default;
    }

    html[data-theme="dark"] .calendar-day.other-month {
        background-color: rgba(255, 255, 255, 0.02);
        color: #475569;
    }
    
    .calendar-day.other-month:hover {
        transform: none;
        border-color: #e5e7eb;
        background-color: #f9fafb;
    }
    
    .day-number {
        font-weight: 600;
        color: #1f2937;
        font-size: 0.875rem;
        margin-bottom: 0.25rem;
    }

    html[data-theme="dark"] .day-number {
        color: #e2e8f0;
    }
    
    .task-indicators {
        display: flex;
        gap: 3px;
        flex-wrap: wrap;
        justify-content: center;
        margin-top: auto;
    }
    
    .task-dot {
        width: 6px;
        height: 6px;
        border-radius: 50%;
        display: inline-block;
    }
    
    .task-dot-work { background-color: #2563eb; }
    .task-dot-learning { background-color: #10b981; }
    .task-dot-personal { background-color: #f59e0b; }
    
    /* Legend Styles */
    .category-legend { display: flex; flex-direction: column; gap: 0.875rem; }
    .legend-item { display: flex; align-items: center; gap: 0.75rem; }
    .legend-dot { width: 12px; height: 12px; border-radius: 50%; }
    .legend-label { font-weight: 500; color: #4b5563; font-size: 0.875rem; }

    html[data-theme="dark"] .legend-label { color: #cbd5e1; }
    
    .stat-item { padding-bottom: 0.75rem; border-bottom: 1px solid #e5e7eb; }
    html[data-theme="dark"] .stat-item { border-bottom: 1px solid #1f2937; }
    .stat-item:last-child { border-bottom: none; padding-bottom: 0; }
    
    .btn-light {
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 0.5rem 1rem;
        transition: all 0.2s ease;
    }
    html[data-theme="dark"] .btn-light { border-color: #1f2937; }
    .btn-light:hover { background-color: var(--bg-light); border-color: #d1d5db; }
    
    /* Modal Styles */
    .modal-content { border-radius: 16px; }
    
    .task-item-modal {
        padding: 0.875rem;
        border-left: 3px solid;
        background-color: #f9fafb;
        border-radius: 6px;
        margin-bottom: 0.75rem;
        transition: all 0.2s ease;
        cursor: pointer; /* Indicate clickable */
        position: relative;
    }
    
    html[data-theme="dark"] .task-item-modal {
        background-color: rgba(255, 255, 255, 0.03);
    }
    
    .task-item-modal:hover {
        transform: translateX(4px);
        background-color: #f3f4f6;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }

    html[data-theme="dark"] .task-item-modal:hover {
        background-color: rgba(255, 255, 255, 0.06);
    }

    /* Edit Icon Indicator on Hover */
    .task-item-modal::after {
        content: "\F4CB"; /* Bootstrap pencil icon unicode */
        font-family: "bootstrap-icons";
        position: absolute;
        right: 10px;
        top: 50%;
        transform: translateY(-50%);
        opacity: 0;
        color: #6b7280;
        transition: opacity 0.2s;
    }
    .task-item-modal:hover::after { opacity: 1; }

    html[data-theme="dark"] .task-item-modal::after {
        color: #d1d5db;
    }

    .task-item-modal.task-work { border-left-color: #2563eb; }
    .task-item-modal.task-learning { border-left-color: #10b981; }
    .task-item-modal.task-personal { border-left-color: #f59e0b; }
    
    .task-item-modal:last-child { margin-bottom: 0; }

    .empty-plan {
        padding: 1rem;
        border: 1px dashed #e5e7eb;
        border-radius: 12px;
        background-color: #f9fafb;
    }

    html[data-theme="dark"] .empty-plan {
        border-color: #1f2937;
        background-color: rgba(255, 255, 255, 0.03);
    }

    /* =========================================
       2. FORM MODAL STYLES
       ========================================= */
    
    #addTaskModal .modal-dialog { max-width: 560px; margin: 1.75rem auto; }
    #addTaskModal .modal-content { border-radius: 16px; }
    #addTaskModal .modal-body { position: relative; overflow-y: auto; max-height: 70vh; }

    .btn-add-task, .btn-success {
        background-color: #10b981 !important;
        border-color: #10b981 !important;
        font-weight: 500;
        border-radius: 10px;
        transition: all 0.2s ease;
    }
    .btn-add-task:hover, .btn-success:hover {
        background-color: #059669 !important;
        transform: translateY(-1px);
    }

    .btn-category {
        padding: 0.4rem 0.8rem;
        border-radius: 20px;
        border: 2px solid transparent;
        font-size: 0.85rem;
        transition: all 0.2s ease;
        font-weight: 500;
    }
    
    .btn-work { color: #1e40af; background-color: #dbeafe; border-color: #dbeafe; }
    .btn-learning { color: #065f46; background-color: #d1fae5; border-color: #d1fae5; }
    .btn-personal { color: #92400e; background-color: #fef3c7; border-color: #fef3c7; }
    
    .btn-check:checked + .btn-category {
        border-color: #10b981;
        box-shadow: 0 0 0 2px rgba(16, 185, 129, 0.2);
        transform: translateY(-1px);
    }

    /* Widget Styling */
    .datetime-wrapper { display: flex; gap: 12px; margin-bottom: 1.5rem; }

    .custom-input-box {
        background-color: #ffffff;
        border: 1px solid #e5e7eb;
        color: #111827;
        border-radius: 10px;
        padding: 12px 16px;
        cursor: pointer;
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        user-select: none;
        min-height: 48px;
        transition: all 0.2s;
        box-shadow: 0 1px 2px rgba(0,0,0,0.05);
    }

    .custom-input-box:hover { border-color: #d1d5db; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }
    .custom-input-box.active { border-color: #10b981 !important; box-shadow: 0 0 0 3px rgba(16, 185, 129, 0.15) !important; }

    html[data-theme="dark"] .custom-input-box {
        background-color: #374151;
        border-color: #4b5563;
        color: #f9fafb;
        box-shadow: none;
    }
    html[data-theme="dark"] .custom-input-box:hover { background-color: #4b5563; }

    .date-display-text { font-size: 0.95rem; font-weight: 500; }
    
    .time-section { flex: 1.5; display: flex; align-items: center; justify-content: center; gap: 8px; }
    .time-input-group { display: flex; align-items: center; gap: 4px; padding: 2px 6px; border-radius: 6px; position: relative; cursor: text; min-width: 85px; justify-content: center; }
    
    html:not([data-theme="dark"]) .time-input-group { background: rgba(0,0,0,0.03); }
    html:not([data-theme="dark"]) .time-input-group:hover { background: rgba(0,0,0,0.06); }

    html[data-theme="dark"] .time-input-group { background: rgba(255,255,255,0.1); }
    html[data-theme="dark"] .time-input-group:hover { background: rgba(255,255,255,0.2); }

    .time-input-group input { background: transparent; border: none; width: 100%; outline: none; text-align: center; font-weight: 500; font-size: 0.9rem; text-transform: lowercase; cursor: text; }
    html:not([data-theme="dark"]) .time-input-group input { color: #111827; }
    html[data-theme="dark"] .time-input-group input { color: #ffffff; }
    
    .time-separator { opacity: 0.5; font-weight: 300; pointer-events: none; }

    /* CALENDAR POPUP (INSIDE MODAL) */
    .calendar-popup {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background: #ffffff;
        border-radius: 16px;
        box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
        width: 320px;
        z-index: 2000;
        padding: 20px;
        display: none;
        border: 1px solid #e5e7eb;
        animation: fadeInScale 0.2s cubic-bezier(0.16, 1, 0.3, 1);
    }
    
    html[data-theme="dark"] .calendar-popup {
        background: #1f2937;
        border-color: #374151;
    }

    .calendar-popup.show { display: block; }
    .calendar-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
    .calendar-month-title { font-weight: 700; font-size: 1.1rem; }
    
    html:not([data-theme="dark"]) .calendar-month-title { color: #111827; }
    html[data-theme="dark"] .calendar-month-title { color: #f3f4f6; }

    .calendar-nav-btn { background: none; border: none; cursor: pointer; padding: 4px; border-radius: 50%; transition: background 0.2s; color: #6b7280; }
    .calendar-nav-btn:hover { background: #f3f4f6; color: #111827; }
    html[data-theme="dark"] .calendar-nav-btn:hover { background: #374151; color: white; }

    #modalCalendarGrid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 4px;
        text-align: center;
    }
    
    .calendar-day-label { font-size: 0.75rem; font-weight: 600; padding-bottom: 10px; text-transform: uppercase; color: #9ca3af; }
    
    #modalCalendarGrid .calendar-day { 
        width: 36px; height: 36px; display: flex; align-items: center; justify-content: center; 
        font-size: 0.95rem; border-radius: 50%; cursor: pointer; margin: 0 auto; transition: all 0.2s; 
        background: transparent; border: none; aspect-ratio: auto;
    }
    
    html:not([data-theme="dark"]) #modalCalendarGrid .calendar-day { color: #374151; }
    html:not([data-theme="dark"]) #modalCalendarGrid .calendar-day:hover:not(.selected) { background-color: #f3f4f6; }
    html:not([data-theme="dark"]) #modalCalendarGrid .calendar-day.other-month { color: #e5e7eb; }
    
    html[data-theme="dark"] #modalCalendarGrid .calendar-day { color: #d1d5db; }
    html[data-theme="dark"] #modalCalendarGrid .calendar-day:hover:not(.selected) { background-color: #374151; }
    html[data-theme="dark"] #modalCalendarGrid .calendar-day.other-month { color: #374151; }

    #modalCalendarGrid .calendar-day.selected { background-color: #10b981 !important; color: white !important; font-weight: 600; box-shadow: 0 4px 6px -1px rgba(16, 185, 129, 0.4); }
    #modalCalendarGrid .calendar-day.today { border: 2px solid #10b981; }
    #modalCalendarGrid .calendar-day.empty { cursor: default; }

    /* TIME DROPDOWN */
    .time-dropdown {
        position: absolute;
        top: 110%; left: 0;
        background: #ffffff;
        border-radius: 8px;
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
        width: 130px;
        max-height: 250px;
        overflow-y: auto;
        z-index: 2000;
        display: none;
        border: 1px solid #e5e7eb;
        padding: 4px;
    }
    
    html[data-theme="dark"] .time-dropdown {
        background: #1f2937;
        border-color: #374151;
    }

    .time-dropdown.show { display: block; }
    .time-option { padding: 6px 10px; font-size: 0.85rem; border-radius: 4px; cursor: pointer; text-transform: lowercase; transition: all 0.1s; }
    
    html:not([data-theme="dark"]) .time-option { color: #374151; }
    html:not([data-theme="dark"]) .time-option:hover { background-color: #f3f4f6; color: #10b981; }
    
    html[data-theme="dark"] .time-option { color: #e5e7eb; }
    html[data-theme="dark"] .time-option:hover { background-color: #374151; color: #10b981; }

    .time-option.highlighted { background-color: #10b981; color: white; }

    @keyframes fadeInScale {
        from { opacity: 0; transform: translate(-50%, -45%); }
        to { opacity: 1; transform: translate(-50%, -50%); }
    }

    .datetime-wrapper.disabled .custom-input-box { opacity: 0.5; pointer-events: none; filter: grayscale(0.8); }
    
    /* Edit Mode Visuals */
    .is-editing-mode .modal-title i { color: #f59e0b !important; }
    .is-editing-mode #submitTaskBtn { background-color: #f59e0b !important; border-color: #f59e0b !important; }
    .is-editing-mode #submitTaskBtn:hover { background-color: #d97706 !important; }

    @media (max-width: 576px) {
        .datetime-wrapper { flex-direction: column; }
        .date-section, .time-section { width: 100%; flex: auto; }
    }
</style>
@endpush

@push('scripts')
<script>
    // ============================
    // 1. DATA & STATE MANAGEMENT
    // ============================
    
    // State Editing
    let isEditing = false;
    let editTargetDate = null;
    let editTargetIndex = null;

    const tasksData = {
        '2026-01-03': [
            { title: 'Review Code', category: 'work', time: '09:00', notes: 'Check PR #123' },
            { title: 'Gym', category: 'personal', time: '17:00', notes: 'Leg day' }
        ],
        '2026-01-05': [
            { title: 'Laravel Tutorial', category: 'learning', time: '14:00', notes: '' }
        ]
    };

    const categoryLabels = {
        'work': 'Kerja',
        'learning': 'Belajar',
        'personal': 'Pribadi'
    };

    const monthNames = [
        "Januari", "Februari", "Maret", "April", "Mei", "Juni",
        "Juli", "Agustus", "September", "Oktober", "November", "Desember"
    ];

    let currentCalendarDate = new Date();
    let selectedCalendarDateString = null;

    document.addEventListener('DOMContentLoaded', () => {
        renderCalendar();
        setupMainCalendarListeners();
        setupModalFormLogic();
        updateStats();
        loadCategoryOptionsFromStorage();
    });

    function updateStats() {
        let total = 0;
        Object.values(tasksData).forEach(dayTasks => {
            total += dayTasks.length;
        });
        document.getElementById('statTotal').innerText = total;
    }

    function setupMainCalendarListeners() {
        document.getElementById('prevMonthBtn').addEventListener('click', () => {
            currentCalendarDate.setMonth(currentCalendarDate.getMonth() - 1);
            renderCalendar();
        });

        document.getElementById('nextMonthBtn').addEventListener('click', () => {
            currentCalendarDate.setMonth(currentCalendarDate.getMonth() + 1);
            renderCalendar();
        });
    }

    function renderCalendar() {
        const year = currentCalendarDate.getFullYear();
        const month = currentCalendarDate.getMonth();
        document.getElementById('monthLabel').innerText = `${monthNames[month]} ${year}`;
        const calendarGrid = document.getElementById('mainCalendarGrid');
        
        const headers = Array.from(document.querySelectorAll('.calendar-day-header'));
        calendarGrid.innerHTML = '';
        headers.forEach(header => calendarGrid.appendChild(header));

        const firstDayIndex = new Date(year, month, 1).getDay();
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const daysInPrevMonth = new Date(year, month, 0).getDate();
        const today = new Date();
        
        // Previous Month
        for (let i = firstDayIndex; i > 0; i--) {
            const dayDiv = document.createElement('div');
            dayDiv.classList.add('calendar-day', 'other-month');
            dayDiv.innerHTML = `<span class="day-number">${daysInPrevMonth - i + 1}</span>`;
            calendarGrid.appendChild(dayDiv);
        }

        // Current Month
        for (let i = 1; i <= daysInMonth; i++) {
            const dayDiv = document.createElement('div');
            dayDiv.classList.add('calendar-day');
            const dateString = `${year}-${String(month + 1).padStart(2, '0')}-${String(i).padStart(2, '0')}`;
            dayDiv.setAttribute('data-date', dateString);

            if (i === today.getDate() && month === today.getMonth() && year === today.getFullYear()) {
                dayDiv.classList.add('today');
            }

            let indicatorsHtml = '';
            const tasks = tasksData[dateString];
            if (tasks) {
                indicatorsHtml += `<div class="task-indicators">`;
                tasks.forEach(task => {
                    indicatorsHtml += `<span class="task-dot task-dot-${task.category}"></span>`;
                });
                indicatorsHtml += `</div>`;
            }

            dayDiv.innerHTML = `<span class="day-number">${i}</span>${indicatorsHtml}`;

            dayDiv.addEventListener('click', function() {
                const date = this.getAttribute('data-date');
                const dayTasks = tasksData[date];
                showTaskDetails(date, dayTasks || []);
            });

            calendarGrid.appendChild(dayDiv);
        }
    }

    function showTaskDetails(date, tasks) {
        const dateObj = new Date(date);
        const options = { day: 'numeric', month: 'long', year: 'numeric' };
        const formattedDate = dateObj.toLocaleDateString('id-ID', options);
        selectedCalendarDateString = date;
        document.getElementById('modalDate').textContent = formattedDate;
        
        let tasksHtml = '';

        if (!tasks || tasks.length === 0) {
            tasksHtml = `
                <div class="empty-plan text-center">
                    <p class="text-muted mb-3">Tidak ada Rencana</p>
                    <!-- Tombol tambah rencana dari state kosong (opsional, karena footer sudah ada tombol) -->
                </div>
            `;
        } else {
            tasks.forEach((task, index) => {
                // Tambahkan onclick untuk membuka modal edit
                tasksHtml += `
                    <div class="task-item-modal task-${task.category}" onclick="bukaModalEdit('${date}', ${index})">
                        <div class="d-flex justify-content-between align-items-start">
                            <div>
                                <h6 class="mb-1 fw-semibold">${task.title}</h6>
                                <span class="badge rounded-pill category-badge text-bg-${getCategoryBadgeColor(task.category)}">${categoryLabels[task.category] || task.category}</span>
                            </div>
                            <small class="text-muted">
                                <i class="bi bi-clock me-1"></i>${task.time || 'All Day'}
                            </small>
                        </div>
                    </div>
                `;
            });
        }
        
        document.getElementById('taskDetailBody').innerHTML = tasksHtml;
        
        const modal = new bootstrap.Modal(document.getElementById('taskDetailModal'));
        modal.show();
    }

    function getCategoryBadgeColor(cat) {
        if(cat === 'work') return 'primary';
        if(cat === 'learning') return 'success';
        if(cat === 'personal') return 'warning';
        return 'secondary';
    }

    // ============================
    // 2. EDIT & ADD LOGIC
    // ============================

    function openAddTaskModal() {
        resetFormState();
        const modal = new bootstrap.Modal(document.getElementById('addTaskModal'));
        modal.show();
    }

    function openAddTaskModalWithDate(dateString) {
        // Tutup detail modal
        const detailModalEl = document.getElementById('taskDetailModal');
        const detailModalInstance = bootstrap.Modal.getInstance(detailModalEl);
        if (detailModalInstance) detailModalInstance.hide();

        // Reset form (ensure ADD mode)
        resetFormState();
        
        // Set tanggal otomatis dari tanggal yang diklik
        const dateParts = dateString.split('-');
        const newDate = new Date(dateParts[0], dateParts[1] - 1, dateParts[2]);
        selectedDate = newDate;
        currentDate = new Date(newDate);
        updateDateDisplay();
        renderModalCalendar();

        const modal = new bootstrap.Modal(document.getElementById('addTaskModal'));
        modal.show();
    }

    function bukaModalEdit(dateString, index) {
        const task = tasksData[dateString][index];
        if (!task) return;

        isEditing = true;
        editTargetDate = dateString;
        editTargetIndex = index;

        document.getElementById('addTaskModal').classList.add('is-editing-mode');
        document.querySelector('#addTaskModalLabel i').className = 'bi bi-pencil-square-fill me-2';
        document.querySelector('#addTaskModalLabel i').style.color = '#f59e0b';
        document.getElementById('formTitleText').textContent = 'Ubah Rencana';
        document.getElementById('formSubtitleText').textContent = 'Edit detail tugas yang sudah ada';
        document.getElementById('btnText').textContent = 'Simpan Perubahan';
        document.querySelector('#submitTaskBtn i').className = 'bi bi-check-lg me-2';

        document.getElementById('taskTitle').value = task.title;
        document.getElementById('taskNotes').value = task.notes || '';
        
        const radios = document.getElementsByName('taskCategory');
        for(let r of radios) {
            if(r.value === task.category) r.checked = true;
        }

        const [y, m, d] = dateString.split('-').map(Number);
        selectedDate = new Date(y, m - 1, d);
        currentDate = new Date(y, m - 1, d);
        updateDateDisplay();
        renderModalCalendar();

        const timeStr = task.time; 
        if (timeStr && timeStr.includes('–')) {
            const parts = timeStr.split('–');
            document.getElementById('startTimeInput').value = parts[0].trim();
            document.getElementById('endTimeInput').value = parts[1].trim();
            document.getElementById('noSpecificTime').checked = false;
            document.getElementById('datetimeSection').classList.remove('disabled');
            document.getElementById('startTimeInput').disabled = false;
            document.getElementById('endTimeInput').disabled = false;
        } else {
            document.getElementById('noSpecificTime').checked = true;
            document.getElementById('startTimeInput').value = '';
            document.getElementById('endTimeInput').value = '';
            document.getElementById('datetimeSection').classList.add('disabled');
            document.getElementById('startTimeInput').disabled = true;
            document.getElementById('endTimeInput').disabled = true;
        }

        const detailModalEl = document.getElementById('taskDetailModal');
        const detailModalInstance = bootstrap.Modal.getInstance(detailModalEl);
        if (detailModalInstance) detailModalInstance.hide();

        const modal = new bootstrap.Modal(document.getElementById('addTaskModal'));
        modal.show();
    }

    function resetFormState() {
        isEditing = false;
        editTargetDate = null;
        editTargetIndex = null;

        document.getElementById('addTaskModal').classList.remove('is-editing-mode');
        document.querySelector('#addTaskModalLabel i').className = 'bi bi-plus-circle-fill me-2';
        document.querySelector('#addTaskModalLabel i').style.color = '#10b981';
        document.getElementById('formTitleText').textContent = 'Rencana Baru';
        document.getElementById('formSubtitleText').textContent = 'Isi detail tugas kamu';
        document.getElementById('btnText').textContent = 'Tambah Tugas';
        document.querySelector('#submitTaskBtn i').className = 'bi bi-plus-circle me-2';

        document.getElementById('taskForm').reset();
        document.getElementById('taskForm').classList.remove('was-validated');
        document.getElementById('charCount').textContent = '0';

        selectedDate = new Date(); 
        currentDate = new Date();
        updateDateDisplay();
        renderModalCalendar();
        
        document.getElementById('startTimeInput').value = "7:30pm";
        document.getElementById('endTimeInput').value = "8:30pm";
        document.getElementById('datetimeSection').classList.remove('disabled');
        document.getElementById('startTimeInput').disabled = false;
        document.getElementById('endTimeInput').disabled = false;
    }

    function saveTask() {
        const form = document.getElementById('taskForm');
        if (!form.checkValidity()) { 
            form.classList.add('was-validated'); 
            return; 
        }
        
        const isNoTime = document.getElementById('noSpecificTime').checked;
        
        const year = selectedDate.getFullYear();
        const month = String(selectedDate.getMonth() + 1).padStart(2, '0');
        const day = String(selectedDate.getDate()).padStart(2, '0');
        const newFormattedDate = `${year}-${month}-${day}`;
        
        const startTime = document.getElementById('startTimeInput').value;
        const endTime = document.getElementById('endTimeInput').value;
        const formattedTime = isNoTime ? null : `${startTime} – ${endTime}`;

        const taskData = {
            title: document.getElementById('taskTitle').value,
            category: document.querySelector('input[name="taskCategory"]:checked')?.value || 'personal',
            date: newFormattedDate, 
            time: formattedTime || '',
            notes: document.getElementById('taskNotes').value
        };

        if (isEditing) {
            if (tasksData[editTargetDate]) {
                tasksData[editTargetDate].splice(editTargetIndex, 1);
                if (tasksData[editTargetDate].length === 0) delete tasksData[editTargetDate];
            }

            if (!tasksData[newFormattedDate]) tasksData[newFormattedDate] = [];
            tasksData[newFormattedDate].push(taskData);

            tasksData[newFormattedDate].sort((a, b) => {
                if(!a.time) return 1;
                if(!b.time) return -1;
                return a.time.localeCompare(b.time);
            });

            document.getElementById('toastMessage').innerText = "Perubahan berhasil disimpan!";
            document.getElementById('toastSubMessage').innerText = "Data telah diperbarui.";

        } else {
            if (!tasksData[newFormattedDate]) tasksData[newFormattedDate] = [];
            tasksData[newFormattedDate].push(taskData);
            
            document.getElementById('toastMessage').innerText = "Rencana berhasil ditambahkan!";
            document.getElementById('toastSubMessage').innerText = "Tugas telah masuk ke kalender";
        }
        
        const modal = bootstrap.Modal.getInstance(document.getElementById('addTaskModal'));
        modal.hide();
        resetFormState();
        
        renderCalendar();
        updateStats();

        const detailModalEl = document.getElementById('taskDetailModal');
        const detailInstance = bootstrap.Modal.getInstance(detailModalEl);
        
        if (detailInstance && detailInstance._isShown) {
            if (selectedCalendarDateString) {
                 const currentTasks = tasksData[selectedCalendarDateString] || [];
                 showTaskDetails(selectedCalendarDateString, currentTasks);
                 detailInstance.show(); 
            }
        }

        const toast = new bootstrap.Toast(document.getElementById('successToast'));
        toast.show();
    }

    // ============================
    // 3. WIDGET LOGIC (DATE & TIME)
    // ============================
    
    const dateDisplayBox = document.getElementById('dateDisplayBox');
    const dateText = document.getElementById('dateText');
    const calendarPopup = document.getElementById('calendarPopup');
    const calendarTitle = document.getElementById('calendarTitle');
    const modalCalendarGrid = document.getElementById('modalCalendarGrid');
    
    let currentDate = new Date();
    let selectedDate = new Date();

    const startTimeInput = document.getElementById('startTimeInput');
    const endTimeInput = document.getElementById('endTimeInput');
    const startTimeDropdown = document.getElementById('startTimeDropdown');
    const endTimeDropdown = document.getElementById('endTimeDropdown');

    function setupModalFormLogic() {
        document.getElementById('taskForm').addEventListener('submit', function(event) {
            event.preventDefault();
            saveTask();
        });
        
        document.getElementById('taskNotes').addEventListener('input', function() {
            document.getElementById('charCount').textContent = this.value.length;
        });
        
        document.getElementById('noSpecificTime').addEventListener('change', function() {
            const wrapper = document.getElementById('datetimeSection');
            const timeInputs = document.querySelectorAll('#startTimeInput, #endTimeInput');
            if (this.checked) {
                wrapper.classList.add('disabled');
                timeInputs.forEach(input => { input.value = ''; input.disabled = true; });
            } else {
                wrapper.classList.remove('disabled');
                timeInputs.forEach(input => {
                    input.value = (input.id === 'startTimeInput' ? '7:30pm' : '8:30pm');
                    input.disabled = false;
                });
            }
        });

        dateDisplayBox.addEventListener('click', (e) => {
            e.stopPropagation();
            if (document.getElementById('datetimeSection').classList.contains('disabled')) return;
            const isOpen = calendarPopup.classList.contains('show');
            closeAllPopups();
            if (!isOpen) {
                calendarPopup.classList.add('show');
                dateDisplayBox.classList.add('active');
                renderModalCalendar();
            }
        });

        document.getElementById('prevMonth').addEventListener('click', (e) => { e.stopPropagation(); currentDate.setMonth(currentDate.getMonth() - 1); renderModalCalendar(); });
        document.getElementById('nextMonth').addEventListener('click', (e) => { e.stopPropagation(); currentDate.setMonth(currentDate.getMonth() + 1); renderModalCalendar(); });

        setupTimePicker('startTimeInput', 'startTimeDropdown');
        setupTimePicker('endTimeInput', 'endTimeDropdown');

        window.addEventListener('click', closeAllPopups);
        calendarPopup.addEventListener('click', (e) => e.stopPropagation());
        startTimeDropdown.addEventListener('click', (e) => e.stopPropagation());
        endTimeDropdown.addEventListener('click', (e) => e.stopPropagation());

        updateDateDisplay();
    }

    function renderModalCalendar() {
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();
        const monthNamesEn = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
        calendarTitle.textContent = `${monthNamesEn[month]} ${year}`;
        
        const headers = ['Su','Mo','Tu','We','Th','Fr','Sa'];
        modalCalendarGrid.innerHTML = headers.map(h => `<div class="calendar-day-label">${h}</div>`).join('');
        
        const firstDayIndex = new Date(year, month, 1).getDay();
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const today = new Date();

        for (let i = 0; i < firstDayIndex; i++) {
            const emptyDiv = document.createElement('div');
            emptyDiv.className = 'calendar-day empty';
            modalCalendarGrid.appendChild(emptyDiv);
        }

        for (let i = 1; i <= daysInMonth; i++) {
            const dayEl = document.createElement('div');
            dayEl.className = 'calendar-day';
            dayEl.textContent = i;
            if (i === selectedDate.getDate() && month === selectedDate.getMonth() && year === selectedDate.getFullYear()) dayEl.classList.add('selected');
            if (i === today.getDate() && month === today.getMonth() && year === today.getFullYear()) dayEl.classList.add('today');
            dayEl.addEventListener('click', (e) => {
                e.stopPropagation();
                selectedDate = new Date(year, month, i);
                updateDateDisplay();
                calendarPopup.classList.remove('show');
                dateDisplayBox.classList.remove('active');
            });
            modalCalendarGrid.appendChild(dayEl);
        }
    }

    function updateDateDisplay() {
        const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
        const parts = selectedDate.toLocaleDateString('en-US', options).split(',');
        dateText.textContent = `${parts[0]}, ${parts[1]}`;
    }

    function generateTimeOptions() {
        const times = [];
        for (let i = 0; i < 24; i++) {
            for (let j = 0; j < 60; j += 15) {
                const hour = i; const minute = j;
                const period = hour >= 12 ? 'pm' : 'am';
                const displayHour = hour % 12 || 12;
                const displayMinute = minute < 10 ? '0' + minute : minute;
                times.push(`${displayHour}:${displayMinute}${period}`);
            }
        }
        return times;
    }
    const timeOptions = generateTimeOptions();

    function setupTimePicker(inputId, dropdownId) {
        const input = document.getElementById(inputId);
        const dropdown = document.getElementById(dropdownId);
        populateDropdown(dropdown, timeOptions, input);

        input.addEventListener('focus', (e) => {
            e.stopPropagation();
            if (document.getElementById('datetimeSection').classList.contains('disabled')) return;
            document.querySelectorAll('.time-dropdown').forEach(d => { if(d !== dropdown) d.classList.remove('show'); });
            dropdown.classList.add('show');
            input.parentElement.classList.add('active');
            filterDropdown(input.value, dropdown);
        });

        input.addEventListener('input', (e) => { filterDropdown(e.target.value, dropdown); });
        
        input.addEventListener('keydown', (e) => {
            const highlighted = dropdown.querySelector('.time-option.highlighted');
            if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
                e.preventDefault();
                const options = Array.from(dropdown.querySelectorAll('.time-option:not([style*="display: none"])'));
                let currentIndex = options.indexOf(highlighted);
                if (e.key === 'ArrowDown') currentIndex = (currentIndex + 1) % options.length;
                if (e.key === 'ArrowUp') currentIndex = (currentIndex - 1 + options.length) % options.length;
                options.forEach(opt => opt.classList.remove('highlighted'));
                if(options[currentIndex]) {
                    options[currentIndex].classList.add('highlighted');
                    options[currentIndex].scrollIntoView({ block: 'nearest' });
                }
            } else if (e.key === 'Enter') {
                e.preventDefault();
                if (highlighted) { input.value = highlighted.textContent; dropdown.classList.remove('show'); } 
                else { dropdown.classList.remove('show'); }
            }
        });

        dropdown.addEventListener('click', (e) => {
            if (e.target.classList.contains('time-option')) {
                input.value = e.target.textContent;
                dropdown.classList.remove('show');
            }
        });
    }

    function populateDropdown(dropdown, options, input) {
        dropdown.innerHTML = '';
        options.forEach(time => {
            const div = document.createElement('div');
            div.className = 'time-option';
            div.textContent = time;
            if (time === input.value) div.classList.add('highlighted');
            div.addEventListener('mouseover', function() {
                dropdown.querySelectorAll('.time-option').forEach(el => el.classList.remove('highlighted'));
                this.classList.add('highlighted');
            });
            dropdown.appendChild(div);
        });
    }

    function filterDropdown(query, dropdown) {
        const options = dropdown.querySelectorAll('.time-option');
        const lowerQuery = query.toLowerCase();
        let firstVisible = null;
        options.forEach(opt => {
            const text = opt.textContent.toLowerCase();
            if (text.includes(lowerQuery)) {
                opt.style.display = 'block';
                if (!firstVisible) firstVisible = opt;
            } else { opt.style.display = 'none'; }
            opt.classList.remove('highlighted');
        });
        if (firstVisible) { firstVisible.classList.add('highlighted'); firstVisible.scrollIntoView({ block: 'nearest' }); }
    }

    function closeAllPopups() {
        calendarPopup.classList.remove('show');
        dateDisplayBox.classList.remove('active');
        document.querySelectorAll('.time-dropdown').forEach(d => d.classList.remove('show'));
        document.querySelectorAll('.time-input-group').forEach(g => g.classList.remove('active'));
    }

    // ============================
    // 4. CUSTOM CATEGORY LOGIC
    // ============================
    const STORAGE_KEY_CATEGORIES = 'focusday.categories';

    function loadCustomCategories() {
        try {
            const raw = localStorage.getItem(STORAGE_KEY_CATEGORIES);
            const parsed = raw ? JSON.parse(raw) : [];
            return Array.isArray(parsed) ? parsed : [];
        } catch (e) { return []; }
    }

    function saveCustomCategories(items) {
        localStorage.setItem(STORAGE_KEY_CATEGORIES, JSON.stringify(items));
    }

    function slugify(value) {
        return value.toString().trim().toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-');
    }

    function addCategoryOptionToHome(category) {
        const additional = document.getElementById('additionalCategories');
        if (!additional) return;
        const categoryId = 'category' + Date.now() + Math.floor(Math.random() * 1000);
        const newCategory = document.createElement('div');
        newCategory.innerHTML = `<input type="radio" class="btn-check" name="taskCategory" id="${categoryId}" value="${category.key}" autocomplete="off"><label class="btn btn-sm btn-category" for="${categoryId}" style="background-color: ${category.bg}; color: ${category.text};"><i class="bi ${category.icon} me-1"></i>${category.label}</label>`;
        additional.appendChild(newCategory);
    }

    function loadCategoryOptionsFromStorage() {
        const additional = document.getElementById('additionalCategories');
        if (!additional) return;
        additional.innerHTML = '';
        const custom = loadCustomCategories();
        custom.forEach(cat => addCategoryOptionToHome(cat));
    }

    function showAddCategory() {
        const form = document.getElementById('addCategoryForm');
        form.classList.toggle('d-none');
        if (!form.classList.contains('d-none')) document.getElementById('newCategoryName').focus();
    }
    
    function addNewCategory() {
        const categoryName = document.getElementById('newCategoryName').value.trim();
        if (!categoryName) return alert('Mohon isi nama kategori');
        const colors = [{bg:'#fef3c7', text:'#92400e', icon:'bi-palette'}, {bg:'#e0e7ff', text:'#3730a3', icon:'bi-star'}, {bg:'#fce7f3', text:'#9d174d', icon:'bi-heart'}];
        const color = colors[Math.floor(Math.random() * colors.length)];
        const key = slugify(categoryName) || ('kategori-' + Date.now());

        const current = loadCustomCategories();
        const exists = current.some(c => c.key === key || c.label.toLowerCase() === categoryName.toLowerCase());
        if (!exists) {
            current.push({ key, label: categoryName, bg: color.bg, text: color.text, icon: color.icon });
            saveCustomCategories(current);
        }

        loadCategoryOptionsFromStorage();
        document.getElementById('newCategoryName').value = '';
        document.getElementById('addCategoryForm').classList.add('d-none');
    }
</script>
@endpush